### ISSUE TITLE
OpAsQuery failing round trip

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#1397]
### Version

4.6.0-SNAPSHOT

### What happened?

A corner case with OpAsQuery with a failing round trip - detected by @LorenzBuehmann while trying out the service enhancer plugin #1314 (and blaming my code for it :innocent:).
It's not high priority but it makes sense to track it nonetheless.

```java
Query origQuery = QueryFactory.create("SELECT * { GRAPH ?g { BIND(?x AS ?y) }}");
// Structure of pattern: ElementNamedGraph ElementGroup ElementBind
Op origOp = Algebra.compile(origQuery);

Query gotQuery = OpAsQuery.asQuery(origOp);
// Structure of pattern: ElementNamedGraph ElementBind (no ElementGroup in between)
Op gotOp = Algebra.compile(gotQuery);
```

yields:
```
org.apache.jena.sparql.ARQInternalErrorException: compile(Element)/Not a structural element: ElementBind
	at org.apache.jena.sparql.algebra.AlgebraGenerator.broken(AlgebraGenerator.java:564)
	at org.apache.jena.sparql.algebra.AlgebraGenerator.compileUnknownElement(AlgebraGenerator.java:170)
	at org.apache.jena.sparql.algebra.AlgebraGenerator.compileElement(AlgebraGenerator.java:156)
```

### Are you interested in making a pull request?

Maybe

**Comment by afs** [comment]
[JENA-2335](https://issues.apache.org/jira/browse/JENA-2335) is also addressed by the PRs #1403 and #1405.
