### ISSUE TITLE
java error Maximum lock count exceeded

### ISSUE THREAD

**Issue by kdejaeger** [apache/jena#1499]
### Version

4.6.0

### What happened?

We encountered this error after 10 hours of uptime.
The server doesn't recover after this error and it keeps repeating.

### Relevant output and stacktrace

```shell
08:24:43 INFO  Fuseki          :: [65533] Body: Content-Length=876, Content-Type=text/turtle, Charset=null => Turtle : Count=7 Triples=7 Quads=0
08:24:44 INFO  Fuseki          :: [65533] 200 OK (255 ms)
08:24:44 INFO  Fuseki          :: [65534] GET http://localhost:3030/fedora?query=SELECT%20%20?uuid%0AWHERE%0A%20%20%7B%20?subject%20%20%3Chttp://surf.nl/ibron/item/2020/07/uuid%3E%20%20?uuid%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp://surf.nl/ibron/item/2020/07/ibronId%3E%20%20%22surf-acc-ibron-1%22%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp://surf.nl/ibron/source/2020/07/id%3E%20%20%22hbo-kennisbank%22%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp://surf.nl/ibron/item/2020/07/originalIdentifier%3E%20%20%22oai:hbokennisbank.nl:sharekit_hhs:oai:surfsharekit.nl:c947a7ae-a705-408d-a6a4-4017f4232f0d%22%0A%20%20%7D%0A
08:24:44 INFO  Fuseki          :: [65534] Query = SELECT  ?uuid WHERE   { ?subject  <http://surf.nl/ibron/item/2020/07/uuid>  ?uuid ;               <http://surf.nl/ibron/item/2020/07/ibronId>  "surf-acc-ibron-1" ;               <http://surf.nl/ibron/source/2020/07/id>  "hbo-kennisbank" ;               <http://surf.nl/ibron/item/2020/07/originalIdentifier>  "oai:hbokennisbank.nl:sharekit_hhs:oai:surfsharekit.nl:c947a7ae-a705-408d-a6a4-4017f4232f0d"   } 
08:24:45 INFO  Fuseki          :: [65534] 200 OK (161 ms)
08:24:45 INFO  Fuseki          :: [65535] POST http://localhost:3030/fedora
08:24:45 INFO  Fuseki          :: [65535] Update
08:24:45 INFO  Fuseki          :: [65535] 204 No Content (245 ms)
08:24:45 INFO  Fuseki          :: [65536] POST http://localhost:3030/fedora?default
08:24:45 WARN  Fuseki          :: [65536] RC = 500 : Maximum lock count exceeded
java.lang.Error: Maximum lock count exceeded
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.fullTryAcquireShared(ReentrantReadWriteLock.java:535) ~[?:?]
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquireShared(ReentrantReadWriteLock.java:494) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1026) ~[?:?]
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738) ~[?:?]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.beginMultiMode(DatasetGraphTxnCtl.java:333) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.tryNonExclusiveMode(DatasetGraphTxnCtl.java:251) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.enterTransaction(DatasetGraphTxnCtl.java:110) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.begin(DatasetGraphTxnCtl.java:74) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.begin(DatasetGraphTxnCtl.java:99) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.sparql.core.DatasetGraphWrapper.begin(DatasetGraphWrapper.java:265) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.query.text.DatasetGraphText.begin(DatasetGraphText.java:170) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.query.text.DatasetGraphText.begin(DatasetGraphText.java:164) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.HttpAction.begin(HttpAction.java:277) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.HttpAction.beginWrite(HttpAction.java:288) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.GSP_RW.triplesPutPostTxn(GSP_RW.java:171) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.GSP_RW.doPutPostGSP(GSP_RW.java:160) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.GSP_RW.execPostGSP(GSP_RW.java:77) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.GSP_RW.doPost(GSP_RW.java:74) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionREST.doPost$(ActionREST.java:97) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionREST.execute(ActionREST.java:46) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionService.executeLifecycle(ActionService.java:58) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionREST.execAny(ActionREST.java:160) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionProcessor.execPost(ActionProcessor.java:48) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionProcessor.process(ActionProcessor.java:34) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionBase.process(ActionBase.java:54) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execActionSub(ActionExecLib.java:124) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:98) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:164) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.server.Dispatcher.process(Dispatcher.java:156) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.fuseki.server.Dispatcher.dispatch(Dispatcher.java:83) ~[fuseki-server.jar:4.6.0]
...
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
08:24:45 INFO  Fuseki          :: [65536] 500 Server Error (7 ms)
08:24:45 INFO  Fuseki          :: [65537] GET http://localhost:3030/fedora?query=SELECT%20%20?uuid%0AWHERE%0A%20%20%7B%20?subject%20%20%3Chttp://surf.nl/ibron/item/2020/07/uuid%3E%20%20?uuid%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp://surf.nl/ibron/item/2020/07/ibronId%3E%20%20%22surf-acc-ibron-1%22%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp://surf.nl/ibron/source/2020/07/id%3E%20%20%22hbo-kennisbank%22%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Chttp://surf.nl/ibron/item/2020/07/originalIdentifier%3E%20%20%22oai:hbokennisbank.nl:sharekit_hhs:oai:surfsharekit.nl:c9db4e27-78b5-45c0-a3ea-a538f529a0e2%22%0A%20%20%7D%0A
08:24:45 INFO  Fuseki          :: [65537] Query = SELECT  ?uuid WHERE   { ?subject  <http://surf.nl/ibron/item/2020/07/uuid>  ?uuid ;               <http://surf.nl/ibron/item/2020/07/ibronId>  "surf-acc-ibron-1" ;               <http://surf.nl/ibron/source/2020/07/id>  "hbo-kennisbank" ;               <http://surf.nl/ibron/item/2020/07/originalIdentifier>  "oai:hbokennisbank.nl:sharekit_hhs:oai:surfsharekit.nl:c9db4e27-78b5-45c0-a3ea-a538f529a0e2"   } 
08:24:45 WARN  Fuseki          :: [65537] RC = 500 : Maximum lock count exceeded
java.lang.Error: Maximum lock count exceeded
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.fullTryAcquireShared(ReentrantReadWriteLock.java:535) ~[?:?]
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquireShared(ReentrantReadWriteLock.java:494) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1026) ~[?:?]
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738) ~[?:?]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.beginMultiMode(DatasetGraphTxnCtl.java:333) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.tryNonExclusiveMode(DatasetGraphTxnCtl.java:251) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.enterTransaction(DatasetGraphTxnCtl.java:110) ~[fuseki-server.jar:4.6.0]
	at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.beg
```

### Are you interested in making a pull request?

No

**Comment by afs** [comment]
Hi @kdejaeger 

Couple of information points:

Was it working with 4.5.0? or is this a new installation?

What's the server work load? In the 10 hours, very approximately, how many writes did the server receive?

(I shortened the stacktrace - but I've got a local copy of the full original)

**Comment by kdejaeger** [comment]
In 4.5.0 I haven't encountered this message.
Around 1 to 2 writes per second.
I will reboot the server later today, let it do it all over again to see what's going to happen.

**Comment by afs** [comment]
At first impression ... it will happen again.

65536 is 2^16.

javadoc of `ReentrantReadWriteLock`
```
 * <p>This lock supports a maximum of 65535 recursive write locks
 * and 65535 read locks. Attempts to exceed these limits result in
 * {@link Error} throws from locking methods.
```
The lock at fault is used for both read and write Fuseki operations, and both take it in "read" mode. (the "write" is exclusive access to finalize compaction).

**Comment by kdejaeger** [comment]
So it's like counting up for each operation. That must be a new bug since 4.6. I'll confirm when it happens again.

**Comment by afs** [comment]
Yes, it is 4.6.0-added code.

The code is taking the lock twice and releasing it once for writes, and taking the lock once and not releasing it for reads. A build up of one per-transaction.

**Comment by kdejaeger** [comment]
Hello, it happened again after 14 hours of uptime. I see you found the place to fix the bug, hopefully for a 4.6.1 release.

**Comment by afs** [comment]
Yes, there will be a 4.6.1 "soon" with the fix in it.

**Comment by afs** [comment]
Hi @MnifOmar - thanks for the report.

Could you say some more about usage?

What's recursive? Is that in the application code?
What operations are in the requests?

> ~65k HTTP requests on Fuseki 5.4.0 (TDB2)

Is this consistent, i.e. after some number of queries the problem arises, or the failure point changes so it isn't exactly the same point?

Do the requesys up to 65k return 200s?

And - ideally - do you have stack trace?

**Comment by MnifOmar** [comment]
@afs  My apologies for not including a stack trace earlier. I’ve since updated my code to explicitly call `connection.commit()` and then `connection.end()` in a `finally` block, and that resolved the issue.

In my case, the problem was triggered by a recursive function in my Java code that executes a very large number of SPARQL queries. The stack trace I encountered was the same as the one already reported above:
```
java.lang.Error: Maximum lock count exceeded... 
```

here is my updated function 
    @Override
    public void select(String query, Consumer<List<QuerySolution>> action) {
        List<QuerySolution> solutions = new ArrayList<>();
        try {
            connection.begin(ReadWrite.READ);
            var q = QueryFactory.create(query);
            connection.querySelect(q, solutions::add);
            connection.commit();
            action.accept(solutions);
        } catch (Exception e) {
            Log.error("Error executing query on remote triple store: {}", e.getMessage(), e);
            throw new RuntimeException("Error retrieving triples from remote triple store", e);
        } finally {
            connection.end();
        }
    }

**Comment by afs** [comment]
Glad you found a way to get the application to work.
