### ISSUE TITLE
NPE is parsing Fuseki Assembler file that used to work in 3.14.0

### ISSUE THREAD

**Issue by eroux** [apache/jena#1524]
### Version

4.6.1

### What happened?

I installed a new instance of Fuseki 4.6.1 and used an assembler file that used to work in our previous 3.14.0 instance. The assembler file is the following:

[core.ttl.zip](https://github.com/apache/jena/files/9533436/core.ttl.zip)

### Relevant output and stacktrace

```shell
The stacktrace is


09-Sep-2022 07:47:03.149 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Shiro environment
09-Sep-2022 07:47:04.340 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.apache.jena.fuseki.webapp.FusekiServerListener]
	org.apache.jena.assembler.exceptions.AssemblerException: caught: null
  doing:
    root: http://base/#core_lucene_index with type: http://jena.apache.org/text#TextIndexLucene assembler class: class org.apache.jena.query.text.assembler.TextIndexLuceneAssembler
    root: http://base/#core_text_dataset with type: http://jena.apache.org/text#TextDataset assembler class: class org.apache.jena.query.text.assembler.TextDatasetAssembler

		at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:165)
		at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.open(AssemblerGroup.java:144)
		at org.apache.jena.assembler.assemblers.AssemblerGroup$ExpandingAssemblerGroup.open(AssemblerGroup.java:93)
		at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:39)
		at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:35)
		at org.apache.jena.query.text.assembler.TextDatasetAssembler.open(TextDatasetAssembler.java:68)
		at org.apache.jena.query.text.assembler.TextDatasetAssembler.open(TextDatasetAssembler.java:42)
		at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:157)
		at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.open(AssemblerGroup.java:144)
		at org.apache.jena.assembler.assemblers.AssemblerGroup$ExpandingAssemblerGroup.open(AssemblerGroup.java:93)
		at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:39)
		at org.apache.jena.assembler.assemblers.AssemblerBase.open(AssemblerBase.java:35)
		at org.apache.jena.fuseki.build.FusekiConfig.getDataset(FusekiConfig.java:667)
		at org.apache.jena.fuseki.build.FusekiConfig.buildDataService(FusekiConfig.java:430)
		at org.apache.jena.fuseki.build.FusekiConfig.buildDataAccessPoint(FusekiConfig.java:417)
		at org.apache.jena.fuseki.build.FusekiConfig.readConfiguration(FusekiConfig.java:397)
		at org.apache.jena.fuseki.build.FusekiConfig.readConfigurationDirectory(FusekiConfig.java:376)
		at org.apache.jena.fuseki.webapp.FusekiWebapp.initializeDataAccessPoints(FusekiWebapp.java:221)
		at org.apache.jena.fuseki.webapp.FusekiServerListener.serverInitialization(FusekiServerListener.java:97)
		at org.apache.jena.fuseki.webapp.FusekiServerListener.contextInitialized(FusekiServerListener.java:57)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4717)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5179)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1027)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2001)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:828)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:478)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1708)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:320)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:795)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
	Caused by: java.lang.NullPointerException
		at java.base/java.util.Hashtable.put(Hashtable.java:475)
		at org.apache.jena.query.text.analyzer.Util.defineAnalyzer(Util.java:93)
		at org.apache.jena.query.text.assembler.DefineAnalyzersAssembler.open(DefineAnalyzersAssembler.java:120)
		at org.apache.jena.query.text.assembler.TextIndexLuceneAssembler.open(TextIndexLuceneAssembler.java:135)
		at org.apache.jena.query.text.assembler.TextIndexLuceneAssembler.open(TextIndexLuceneAssembler.java:40)
		at org.apache.jena.assembler.assemblers.AssemblerGroup$PlainAssemblerGroup.openBySpecificType(AssemblerGroup.java:157)
		... 60 more
09-Sep-2022 07:47:04.372 INFO [main] org.apache.catalina.core.ApplicationContext.log Cleaning up Shiro Environment
09-Sep-2022 07:47:04.687 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
09-Sep-2022 07:47:04.687 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
09-Sep-2022 07:47:04.688 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@5a90df0')
```

### Are you interested in making a pull request?

Maybe

**Comment by afs** [comment]
Could you provide a minimal example assembler?

**Comment by eroux** [comment]
Is this minimal enough?

```ttl
@prefix fuseki:  <http://jena.apache.org/fuseki#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix tdb:     <http://jena.hpl.hp.com/2008/tdb#> .
@prefix tdb2:    <http://jena.apache.org/2016/tdb#> .
@prefix ja:      <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix :        <http://base/#> .
@prefix text:    <http://jena.apache.org/text#> .
@prefix skos:    <http://www.w3.org/2004/02/skos/core#> .
@prefix adm:     <http://purl.bdrc.io/ontology/admin/> .
@prefix bdo:     <http://purl.bdrc.io/ontology/core/> .
@prefix bdr:     <http://purl.bdrc.io/resource/> .


[] rdf:type fuseki:Server ;
   fuseki:services (
     :corerw
   ) .

:corerw rdf:type fuseki:Service ;
    fuseki:name                       "corerw" ;     # name of the dataset in the url
    fuseki:serviceQuery               "query" ;    # SPARQL query service
    fuseki:dataset                    :core_text_dataset ;
    .

:core_text_dataset rdf:type     text:TextDataset ;
    text:dataset   :dataset_core ;
    text:index     :core_lucene_index ;
    .

# using TDB
:dataset_core rdf:type      tdb:DatasetTDB ;
     tdb:location "/usr/local/fuseki/base/databases/core" ;
     tdb:unionDefaultGraph true ;
     .

# Text index description
:core_lucene_index a text:TextIndexLucene ;
    text:directory <file:/usr/local/fuseki/base/lucene-core> ;
    text:storeValues true ;
    text:multilingualSupport true ;
    text:ignoreIndexErrors true ;
    text:defineAnalyzers (
        [ text:defineAnalyzer :kmUniAnalyzer ; 
          text:analyzer [ 
            a text:GenericAnalyzer ;
            text:class "io.bdrc.lucene.km.KhmerAnalyzer" ;
            text:params (
                [ text:paramName "normalizationlevel" ;
                  text:paramValue 3 ]
                )
            ] ; 
          ]
        [ text:addLang "km" ;
          text:searchFor ( "km" "pi-khmr" ) ;
          text:analyzer [ 
            a text:DefinedAnalyzer ; 
            text:useAnalyzer :kmUniAnalyzer ;
            ] ;
          ]
      ) ;
    .

```

**Comment by afs** [comment]
> text:class "io.bdrc.lucene.km.KhmerAnalyzer" ;

It depends on private code. Given the jump in versions, including java8 -> java11, that might be an issue. The code doe snot trap all class load possible problems, only "not found".

>    text:storeValues true ;
    text:multilingualSupport true ;
    text:ignoreIndexErrors true ;
    text:defineAnalyzers (

Too many things I'm not familiar with.
I'll leave this with you for now.

**Comment by eroux** [comment]
great

**Comment by eroux** [comment]
after some debugging, it turns out this is triggered by the missing class `"io.bdrc.lucene.km.KhmerAnalyzer"`. There's a try / catch block but for some reason the error doesn't appear in `tomcat/logs/localhost.2022-09-09.log`, it's only when reproducing it locally in eclipse that I was able to see it. When testing locally though the NPE also appears, so there seems to be some issue further down the line when this exception occurs...

I'll close this since I won't debug further but I hope this issue might help people encountering the same issue
