### ISSUE TITLE
FusekiMainCMD

### ISSUE THREAD

**Issue by Bearshanjun** [apache/jena#1528]
### Version

4.6.1

### Question

I use Maven to compile the source code and no error, but run FusekiMainCmd error, related information is as follows.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/jena/ext/com/google/common/cache/RemovalNotification
	at org.apache.jena.atlas.lib.cache.CacheGuava.<init>(CacheGuava.java:41)
	at org.apache.jena.atlas.lib.CacheFactory.createCache(CacheFactory.java:31)
	at org.apache.jena.enhanced.EnhGraph.<init>(EnhGraph.java:41)
	at org.apache.jena.rdf.model.impl.ModelCom.<init>(ModelCom.java:76)
	at org.apache.jena.rdf.model.impl.ModelCom.<init>(ModelCom.java:73)
	at org.apache.jena.rdf.model.ModelFactory.createDefaultModel(ModelFactory.java:91)
	at org.apache.jena.vocabulary.DC_11.<clinit>(DC_11.java:29)
	at org.apache.jena.shared.PrefixMapping.<clinit>(PrefixMapping.java:221)
	at org.apache.jena.sparql.ARQConstants.<clinit>(ARQConstants.java:114)
	at org.apache.jena.query.ARQ.init(ARQ.java:627)
	at org.apache.jena.sparql.system.InitARQ.start(InitARQ.java:29)
	at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
	at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88)
	at arq.cmdline.CmdARQ.<clinit>(CmdARQ.java:30)
	at org.apache.jena.fuseki.main.cmds.FusekiMainCmd.main(FusekiMainCmd.java:47)
```
My environment is

    mvn 3.8.6, jdk 11-16

I tried to search for “org/apache/jena/ext/com/google/common/cache/RemovalNotification” in idea and only found import in AsyncClaimingCacheImplGuava, I can confirm that it was loaded properly

![image](https://user-images.githubusercontent.com/34940587/189506824-fda4c9e3-6142-4093-a3d3-d4d959b1b1c8.png)

Can you help me determine what the problem is

**Comment by kinow** [comment]
Hmm, I think that could be an issue with the IDE. I remember having to close the shaded module in Eclipse. If you are using Eclipse, try that (close the module-project). Maybe the same fixes the issue in IntelliJ, although I don't know if you have to ignore the module or do something similar - https://github.com/apache/jena/tree/main/jena-shaded-guava

**Comment by afs** [comment]
Sorry it;s not working cleanly first time.

As well as excluding `jena-shaded-guava` as @iknow notes, close or don't import, the top level project. It ends up with two routes to everything which can confuse IDEs.

Which IDE do you use? We can expand the build instructions for the next person who encounters these issues.

**Comment by Bearshanjun** [comment]
Thanks guys, I use IDEA 2022.2.1 , I hope it can help you

**Comment by LorenzBuehmann** [comment]
With IntelliJ IDE you can just disable the `jena-shaded-guava` module and it will use the dependency from public Maven repo.

**Comment by afs** [comment]
Yes - the best way is to omit `jena-shaded-guava` (IntelliJ or Eclipse).

@Bearshanjun -- does this work for you?

**Comment by Bearshanjun** [comment]
Of course, thanks again for your help
