### ISSUE TITLE
How to restore from a fuseki backup

### ISSUE THREAD

**Issue by kdejaeger** [apache/jena#1532]
### Version

4.6.1

### Question

I can't seems to figure out how to load a *.ng backup into a new fuseki instance.

Through the GUI, I get this error:
`
14:38:37 INFO  Fuseki          :: [33] POST http://localhost:3030/fedora/data
14:38:37 ERROR Fuseki          :: [line: 1, col: 7 ] Element or attribute do not match QName production: QName::=(NCName':')?NCName. 
14:38:43 INFO  Fuseki          :: [33] Upload error: [line: 1, col: 7 ] Element or attribute do not match QName production: QName::=(NCName':')?NCName. 
14:38:43 INFO  Fuseki          :: [33] 500 Server Error (6.539 s)
`

With the tdbloader I get this error:
`
root@fb3db45c4b92:/jena-fuseki# /jena/bin/tdbloader2 --loc /fuseki-base/databases/fedora/ /home/koen/tmp/backup.ng
tdbloader2 has been renamed tdb1.xloader
root@fb3db45c4b92:/jena-fuseki# /jena/bin/tdbloader2 --loc /fuseki-base/databases/fedora/ /home/koen/tmp/backup.ng.gz 
tdbloader2 has been renamed tdb1.xloader
`

I also tried this:

root@ibron--surf-acc-ibron-1-7bb4d4dd8d-h5jhd:/jena-fuseki# java -cp /jena-fuseki/fuseki-server.jar:/javalibs/* tdb2.tdbloader --loc=/fuseki-base/databases/fedora/ /tmp/backup.ng
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/jena-fuseki/fuseki-server.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/javalibs/silk-arq-1.0.0-SNAPSHOT-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
15:04:25 INFO  loader          :: Loader = LoaderBasic
15:04:25 INFO  loader          :: Start: /tmp/backup.ng
org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=file:///tmp/backup.ng : stream=null)
        at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:380)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:360)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:568)
        at org.apache.jena.tdb2.loader.base.LoaderOps.inputFile(LoaderOps.java:107)
        at org.apache.jena.tdb2.loader.base.LoaderBase.loadOne(LoaderBase.java:139)
        at org.apache.jena.tdb2.loader.base.LoaderBase.lambda$load$0(LoaderBase.java:106)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.apache.jena.tdb2.loader.base.LoaderBase.load(LoaderBase.java:103)
        at tdb2.tdbloader.lambda$execBulkLoad$3(tdbloader.java:186)
        at org.apache.jena.atlas.lib.Timer.time(Timer.java:86)
        at tdb2.tdbloader.execBulkLoad(tdbloader.java:184)
        at tdb2.tdbloader.loadQuads(tdbloader.java:175)
        at tdb2.tdbloader.exec(tdbloader.java:135)
        at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:87)
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:56)
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:43)
        at tdb2.tdbloader.main(tdbloader.java:63)

root@ibron--surf-acc-ibron-1-7bb4d4dd8d-h5jhd:/jena-fuseki# ls -lh /tmp
total 111M
-rw-r--r-- 1 1000 users  98M Sep 13 15:01 backup.ng
-rw-r--r-- 1 1000 users  13M Sep 13 15:03 backup.ng.gz
drwxr-xr-x 1 root root  4.0K Sep 13 15:04 hsperfdata_root

root@ibron--surf-acc-ibron-1-7bb4d4dd8d-h5jhd:/jena-fuseki# file --mime-type /tmp/backup.ng
/tmp/backup.ng: application/octet-stream

**Comment by kdejaeger** [comment]
I also tried this:

> root@ibron--surf-acc-ibron-1-7bb4d4dd8d-h5jhd:/jena-fuseki# java -cp /jena-fuseki/fuseki-server.jar:/javalibs/* tdb2.tdbloader --loc=/fuseki-base/databases/fedora/ /tmp/backup.ng
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/jena-fuseki/fuseki-server.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/javalibs/silk-arq-1.0.0-SNAPSHOT-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
15:04:25 INFO  loader          :: Loader = LoaderBasic
15:04:25 INFO  loader          :: Start: /tmp/backup.ng
org.apache.jena.riot.RiotException: Failed to determine the content type: (URI=file:///tmp/backup.ng : stream=null)
        at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:380)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:360)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:568)
        at org.apache.jena.tdb2.loader.base.LoaderOps.inputFile(LoaderOps.java:107)
        at org.apache.jena.tdb2.loader.base.LoaderBase.loadOne(LoaderBase.java:139)
        at org.apache.jena.tdb2.loader.base.LoaderBase.lambda$load$0(LoaderBase.java:106)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.apache.jena.tdb2.loader.base.LoaderBase.load(LoaderBase.java:103)
        at tdb2.tdbloader.lambda$execBulkLoad$3(tdbloader.java:186)
        at org.apache.jena.atlas.lib.Timer.time(Timer.java:86)
        at tdb2.tdbloader.execBulkLoad(tdbloader.java:184)
        at tdb2.tdbloader.loadQuads(tdbloader.java:175)
        at tdb2.tdbloader.exec(tdbloader.java:135)
        at org.apache.jena.cmd.CmdMain.mainMethod(CmdMain.java:87)
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:56)
        at org.apache.jena.cmd.CmdMain.mainRun(CmdMain.java:43)
        at tdb2.tdbloader.main(tdbloader.java:63)
root@ibron--surf-acc-ibron-1-7bb4d4dd8d-h5jhd:/jena-fuseki# ls -lh /tmp
total 111M
-rw-r--r-- 1 1000 users  98M Sep 13 15:01 backup.ng
-rw-r--r-- 1 1000 users  13M Sep 13 15:03 backup.ng.gz
drwxr-xr-x 1 root root  4.0K Sep 13 15:04 hsperfdata_root
root@ibron--surf-acc-ibron-1-7bb4d4dd8d-h5jhd:/jena-fuseki# file --mime-type /tmp/backup.ng
/tmp/backup.ng: application/octet-stream

**Comment by rvesse** [comment]
Jena does not recognise the `.ng` file extension you used.

Fuseki backups are written as NQuads files for which the normal extension is `.nq`

So either try renaming the backup file appropriately to use this extension, or you can try explicitly stating the RDF serialisation to the loader command. This is usually done via the `--lang` or `--syntax` options (I can't remember which applies to this command off the top of my head, run with `--help` to see the options for the command)

**Comment by kdejaeger** [comment]
Ok thanks, I didn't notice renamed it wrongly.
