### ISSUE TITLE
downloading geosparql binary and using with fuseki-webapp results in NoClassDefFoundError:

### ISSUE THREAD

**Issue by OyvindLGjesdal** [apache/jena#1588]
### Version

4.6.1

### What happened?

Following the instructions from https://jena.apache.org/documentation/geosparql/geosparql-assembler.html

1. Download fuseki binary and configure 
2. Download binary from maven central for jena-geosparql-4.6.1.jar (313.9 KB) and place in $FUSEKI_BASE/extra
3. ./fuseki-server (or starting as a service from ./fuseki-server)

results in stacktrace below

assembler file used is (stedsnavn-geo.ttl, lightly changed copy of assembler in documentation )
```
REFIX fuseki:    <http://jena.apache.org/fuseki#>
PREFIX rdf:       <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:      <http://www.w3.org/2000/01/rdf-schema#>
PREFIX tdb2:      <http://jena.apache.org/2016/tdb#>

PREFIX ja:        <http://jena.hpl.hp.com/2005/11/Assembler#>
PREFIX geosparql: <http://jena.apache.org/geosparql#>

<#service> rdf:type fuseki:Service;
    fuseki:name "stedsnavn-geo";
    fuseki:endpoint [ fuseki:operation fuseki:query; ] ;
    fuseki:dataset <#geo_ds> .

<#geo_ds> rdf:type geosparql:GeosparqlDataset ;
    geosparql:spatialIndexFile     "/var/fuseki/databases/stedsnavn-geo/spatial.index";
    geosparql:dataset <#baseDataset> ;
    .

<#baseDataset> rdf:type tdb2:DatasetTDB2 ;
    tdb2:location "/var/fuseki/databases/stedsnavn-geo/" ;
    .
```
When I then view the binary download jar file in an archive app, I only see the the `org/apache` path, should also the dependencies listed in the `jena-geosparql/pom.xml` be present in the jar? (e.g shaded?)

### Relevant output and stacktrace

```shell
Oct 25 22:59:12 fuseki-test.novalocal systemd[1]: Started Fuseki.
Oct 25 22:59:12 fuseki-test.novalocal fuseki-server[2147]: FUSEKI BASE /var/fuseki
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: Exception in thread "main" java.lang.NoClassDefFoundError: org/jdom2/JDOMException
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.geosparql.implementation.datatype.GeometryDatatype.registerDatatypes(GeometryDatatype.java:69)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.geosparql.InitGeoSPARQL.start(InitGeoSPARQL.java:38)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at arq.cmdline.CmdARQ.<clinit>(CmdARQ.java:30)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:67)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: Caused by: java.lang.ClassNotFoundException: org.jdom2.JDOMException
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Oct 25 22:59:13 fuseki-test.novalocal fuseki-server[2147]: ... 10 more
```

### Are you interested in making a pull request?

Maybe

**Comment by OyvindLGjesdal** [comment]
doh, I downloaded the wrong jar, the correct one should be https://repo1.maven.org/maven2/org/apache/jena/jena-fuseki-geosparql/4.6.1/jena-fuseki-geosparql-4.6.1.jar and not jena-geosparql-4.6.1.jar.
