### ISSUE TITLE
Sorting fails with custom datatype literal

### ISSUE THREAD

**Issue by LorenzBuehmann** [apache/jena#1634]
### Version

4.7.0-SNAPSHOT

### What happened?

Dataset: some DBpedia stuff

Query ("give me longest river"):
``` sparql
SELECT DISTINCT ?uri WHERE {
  ?uri a <http://dbpedia.org/ontology/River> 
  {
    ?uri <http://dbpedia.org/ontology/length> ?l 
  } UNION {
    ?uri <http://dbpedia.org/property/length> ?l 
  } 
}
ORDER BY DESC(?l) OFFSET 0 LIMIT 1
```
it fails with 500 and "Comparison method violates its general contract!".

DBpedia data is annoying anyways, there are plenty of length literals with different datatype. For debugging I reduced the literal mix to two :`xsd:double,  	<http://dbpedia.org/datatype/kilometre>`

``` sparql
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?uri WHERE {
  ?uri a <http://dbpedia.org/ontology/River> 
  {
    ?uri <http://dbpedia.org/ontology/length> ?l 
  } UNION {
    ?uri <http://dbpedia.org/property/length> ?l 
  } 
  filter(datatype(?l) in (xsd:double,  	<http://dbpedia.org/datatype/kilometre>))
}
ORDER BY DESC(?l) OFFSET 0 LIMIT 1
```
which still fails.

It does not fail if we project/select the length literal `?l` though:

```sparql
SELECT DISTINCT ?uri ?l WHERE {
  ?uri a <http://dbpedia.org/ontology/River> 
  {
    ?uri <http://dbpedia.org/ontology/length> ?l 
  } UNION {
    ?uri <http://dbpedia.org/property/length> ?l 
  } 
  filter(datatype(?l) in (xsd:double,  	<http://dbpedia.org/datatype/kilometre>))
}
ORDER BY DESC(?l) OFFSET 0 LIMIT 1
```

Looking for the Java exception I found source like here: https://bugs.openjdk.org/browse/JDK-8234482
which also does contain a hint that timsort needs sufficient amount of data to fail:
> TimSort doesn't throw this exception in all cases, though, only if there are a sufficiently large number of elements to be merged (generally > 32 elements, often hundreds are required), and if the sorting algorithm happens to detect an contradiction in the comparison method.

The JDK version is Java 11 by the way if that matters.

### Relevant output and stacktrace

```shell
Query = PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>  SELECT DISTINCT ?uri WHERE {   ?uri a <http://dbpedia.org/ontology/River>    {     ?uri <http://dbpedia.org/ontology/length> ?l    } UNION {     ?uri <http://dbpedia.org/property/length> ?l    }    filter(datatype(?l) in (xsd:double,  	<http://dbpedia.org/datatype/kilometre>)) } ORDER BY DESC(?l) OFFSET 0 LIMIT 1
10:12:42 WARN  Fuseki          :: [32] RC = 500 : Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
	at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
	at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1441) ~[?:?]
	at org.apache.jena.atlas.data.AbortableComparator.abortableSort(AbortableComparator.java:57) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.atlas.data.SortedDataBag.iterator(SortedDataBag.java:205) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.atlas.data.SortedDataBag.iterator(SortedDataBag.java:192) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIterSort$SortedBindingIterator.initializeIterator(QueryIterSort.java:88) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.atlas.iterator.IteratorDelayedInitialization.init(IteratorDelayedInitialization.java:38) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.atlas.iterator.IteratorDelayedInitialization.hasNext(IteratorDelayedInitialization.java:48) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:59) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.getInputNextUnseen(QueryIterDistinct.java:113) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.hasNextBinding(QueryIterDistinct.java:72) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIterSlice.hasNextBinding(QueryIterSlice.java:76) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.exec.RowSetStream.hasNext(RowSetStream.java:47) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:81) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeQuery(SPARQLQueryProcessor.java:380) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:279) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeWithParameter(SPARQLQueryProcessor.java:224) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:209) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.ActionService.executeLifecycle(ActionService.java:58) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execPost(SPARQLQueryProcessor.java:84) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.ActionProcessor.process(ActionProcessor.java:34) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.ActionBase.process(ActionBase.java:54) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execActionSub(ActionExecLib.java:124) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:98) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:164) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.server.Dispatcher.process(Dispatcher.java:156) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
	at org.apache.jena.fuseki.server.Dispatcher.dispatch(Dispatcher.java:83) ~[fuseki-server.jar:4.7.0-SNAPSHOT]
```
### Steps to reproduce
* unzip attachment
```bash
sparql --data issue_1634.ttl --query issue_1634.rq
```

[issue_1634.zip](https://github.com/apache/jena/files/10084097/issue_1634.zip)

**Comment by afs** [comment]
Could you please turn this into a standalone test case with reduced data?

**Comment by afs** [comment]
Context;

* [JENA-2333](https://issues.apache.org/jira/browse/JENA-2333)
* #1406

**Comment by LorenzBuehmann** [comment]
I attached a "minimal" Turtle file as well as the query file to reproduce the exception. Can you reproduce it when doing

```bash
tdb2.tdbloader --loc /tmp/issue_1634 issue_1634.ttl
tdb2.tdbquery --loc /tmp/issue_1634 --query 
[issue_1634.zip](https://github.com/apache/jena/files/10084086/issue_1634.zip)
issue_1634.rq
```

Also, I'm mostly reporting this because it's probably an exception message something users can't understand when using Fuseki. I'd also fine if we just give a hint to check of filter the datatypes in their query like I'd suggest for people using DBpedia, "hey please only sort on int and double values, omit the rest".

**Comment by LorenzBuehmann** [comment]
[issue_1634.zip](https://github.com/apache/jena/files/10084093/issue_1634.zip)

**Comment by afs** [comment]
It's not minimal.

It won't depend on TDB. 

It will happen with "sparql --data --query" which is somewhat easier to work with. No Fuseki, no DB.

(I'm using OpenJDK17 but from JENA-2333 the Timsort code is the same from 11 onwards.)

**Comment by LorenzBuehmann** [comment]
Regarding the steps, fair enough - I adapted the instruction in the initial post. Regarding size of data, I tried with a lower number of `xsd:double` literals < 1000, in that case it did not fail nor did it fail when reducing the number of custom datatype literals to 10 - so, currently a failing distribution is 
* ~1000 `xsd:double` literals
* ~100 literals with a custom datatype

**Comment by LorenzBuehmann** [comment]
By the way, what's the difference in sorting with and without projecting the sorted variable? With selection of `?l` it doesn't fail

**Comment by rvesse** [comment]
> By the way, what's the difference in sorting with and without projecting the sorted variable? With selection of `?l` it doesn't fail

So the SPARQL specification [section 18.2.5](https://www.w3.org/TR/sparql11-query/#convertSolMod) says that `ORDER BY` is applied prior to `DISTINCT`

**BUT** ARQ includes an optimiser that swaps the ordering i.e. applies `DISTINCT` first in cases where all the variables in the `ORDER BY` are also projected.  This is semantically equivalent and is shown to substantially increase performance because you throw out all the non-distinct solutions prior to ordering.  So in that case every row is guaranteed to be unique and you can't ever get any unstable sorting results as every row is different (at least for your dataset).

I suspect what happens in the failing case is that you have two solutions with the custom datatype literals present and we aren't guaranteeing to provide a stable sort (see PR #1406 that Andy referenced) over those.

**Comment by afs** [comment]
The bug is probably where there are three values get compared during the sort: "A<B" and "B<C" but "A>C".

This needs confirming (is it one double and 2 unknowns or 2 doubles and one unknown - really hope it isn't 3 the same beause that would be completely different and unknown) - and it depends on the lexical forms where for xsd:double lexical form order is not value order.

> Regarding size of data, I tried with a lower number

It's not just "make smaller". It is find some specific reduced set in a particular order. But for a triggering case with "sparql --data --query" it should happen each time (no bnodes to cause different orders per run.)

From JENA-2333, the order that nodes hit the Timsort matters - the sort can be silently wrong as well.

There will be an example with no DISTINCT, no OFFSET/LIMIT, and rdf:type. These change the order arriving at the sort, including different data sizes having different orders for the same query, making finding/confirming the root case harder.

The `sparql` command uses TIM which does not hash tables, chopping up data at least gets indexed in the same order. GraphMem would be hit by hash table expansion reordering input.

```
SELECT (count(*) AS ?C) WHERE {
  ?uri <http://dbpedia.org/ontology/length> ?l .
}
ORDER BY DESC(?l)
```

Unless it's a completely different issue, a fix is doable but the code is not set up for it at the moment. There needs to be a significant refactoring/rewrite and it'll apply to all ORDER BY. That's not something to do in the 4.7.0 timeframe fix.

**Comment by afs** [comment]
This case fails:

```
# Compare (n1, n2) (n2, n3) (n1, n3)
> > <=:  1  1 -1 ::  206000.0e0   98800.0e0   "49.2"^^<http://dbpedia.org/datatype/kilometre>
```

Fortunately it turns up quickly by doing a N^3 expansion and testing 3 elements (there are over a billion cases to try - it is taking a while.)

There are lots of failures. A rate of 3%-4% so far.
