### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 952182 out of bounds for length 635413

### ISSUE THREAD

**Issue by ebremer** [apache/jena#1646]
### Version

4.6.1

### What happened?

Iterating through the results of a SPARQL query on a in-memory graph of 1,051,850 triples using:

ResultSet rs = qe.execSelect();
rs.forEachRemaining(qs->{
   * do the business *
});

### Relevant output and stacktrace

```shell
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 952182 out of bounds for length 635413
	at org.apache.jena.mem.HashCommon.findSlot(HashCommon.java:164)
	at org.apache.jena.mem.HashedBunchMap.get(HashedBunchMap.java:59)
	at org.apache.jena.mem.NodeToTriplesMapMem.iterator(NodeToTriplesMapMem.java:129)
	at org.apache.jena.mem.GraphTripleStoreBase.find(GraphTripleStoreBase.java:161)
	at org.apache.jena.mem.GraphMem.graphBaseFind(GraphMem.java:55)
	at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:229)
	at org.apache.jena.graph.impl.GraphBase.graphBaseFind(GraphBase.java:243)
	at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:240)
	at org.apache.jena.sparql.engine.main.solver.StageMatchTriple.accessTriple(StageMatchTriple.java:60)
	at org.apache.jena.sparql.engine.main.solver.StageMatchTriple.lambda$accessTriple$0(StageMatchTriple.java:48)
	at org.apache.jena.atlas.iterator.IteratorFlatMap.hasNext(IteratorFlatMap.java:57)
	at org.apache.jena.sparql.engine.iterator.IterAbortable.hasNext(IterAbortable.java:59)
	at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:59)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116)
	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116)
	at org.apache.jena.sparql.exec.RowSetStream.hasNext(RowSetStream.java:47)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:81)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
```

**Comment by rvesse** [comment]
Is there a dataset you can share to reproduce this?

Note that `GraphMem` is very old code at this point and I'm not aware that this issue has ever been reported before so it's likely a specific quirk of your data.

There has been an effort underway to replace it with a more modern implementation (see PR #1273) but no ETA on when that will land in a release

**Comment by afs** [comment]
@ebremer 

What's the "do the business " part? Is it in someway updating the data being queried?

A `ResultSet` is a stream from the data, and it stepping through as `.next` is called during the `forEachRemaining`.

To isolate the result set from the data:

```
    ResultSet rs = qe.execSelect().materialise();
```

**Comment by ebremer** [comment]
I was able to fix this last night.  The "do the business" was sending a list of resources and object values from the ResultSet to a ThreadPoolExecutor to process over 64 cores.  Whereas, the individual threads kept mostly to themselves,  each was adding the results back to the original Model as follows:
```
m.enterCriticalSection(Lock.WRITE);
m.add(z);
m.leaveCriticalSection();
```
The code work for thousands of large graphs, but for one, kept throwing the same above error.  I was able to fix the issue by buffering up all of the threads and then calling engine.prestartAllCoreThreads() after the
```
rs.forEachRemaining(qs->{
    do the business *
    });
```
loop was done.  ResultSet rs = qe.execSelect().materialise(); looks like it would have solved the issue too so I will have to give it a try.  Thanks!

**Comment by afs** [comment]
Right - GraphMem is not thread safe. The read side also needs a critical section (read) but the locks are MRSW so writing is single threaded, no reader at the time.

Transaction are better (tm). 

`DatasetFactory.createTxnMem()` and graph from that type of dataset.

```
dataset.executeRead(()->so the query, do the business);
```
and
```
dataset.executeWrite(()->m.add(z));
```

That's MR+SW (multiple readers AND one single writer).
The query is isolated - it does not see changes while running.
