### ISSUE TITLE
Error in configuration file: Reader not found: TURTLE

### ISSUE THREAD

**Issue by namedgraph** [apache/jena#1671]
### Version

4.6.1

### What happened?

Looks like something has changed between 4.5.0 and 4.6.1 re. location mapping.

Jena 4.5.0:
```
StreamManager:175 - Found: etc/location-mapping.ttl (LocatorFile)
JenaIOEnvironment:119 - Mapping: http://xmlns.com/foaf/0.1/ => etc/foaf.owl
JenaIOEnvironment:119 - Mapping: http://spinrdf.org/spl => etc/spl.spin.ttl
JenaIOEnvironment:119 - Mapping: http://spinrdf.org/spl# => etc/spl.spin.ttl
JenaIOEnvironment:119 - Mapping: http://spinrdf.org/spin => etc/spin.ttl
JenaIOEnvironment:119 - Mapping: http://spinrdf.org/spin# => etc/spin.ttl
JenaIOEnvironment:119 - Mapping: http://spinrdf.org/sp => etc/sp.ttl
JenaIOEnvironment:119 - Mapping: http://spinrdf.org/sp# => etc/sp.ttl
```

Jena 4.6.1:
```
StreamManager:175 - Found: etc/location-mapping.ttl (LocatorFile)
LocationMapper:188 - Error in configuration file: Reader not found: TURTLE
```
`JenaSystem::init` is called like this:
```java
static
{
    JenaSystem.init();
}
```
Failing test: https://github.com/AtomGraph/Twirl/blob/jena-4.6.1/src/test/java/com/atomgraph/spinrdf/constraints/InfOntModelConstraintTest.java

### Are you interested in making a pull request?

No

**Comment by kinow** [comment]
Related to: 

- https://github.com/apache/jena/issues/1493

**Comment by afs** [comment]
Those mappings are not from Jena.

> Failing test:

That s a whole bunch of tests with local classes. We'd need a standalone single test case.

**Comment by namedgraph** [comment]
> Those mappings are not from Jena.

No, but does that matter? The point is they were read fine with 4.5.0 but not with 4.6.1.

Isolated test case: https://github.com/namedgraph/Jena-4.6.1-test/blob/main/src/test/java/com/atomgraph/spinrdf/constraints/LocationMappingTest.java

**Comment by afs** [comment]
That's not a test of the report. It works until it encounters parse error from FOAF.
There is no location-mapper setup.

**Comment by namedgraph** [comment]
The log shows that location mapping is found at `etc/location-mapping.ttl`. That's one of the default paths `StreamManager`/`JenaIOEnvironment` [is looking in](https://github.com/apache/jena/blob/31dc0d328c4858401e5d3fa99702c97eba0383a0/jena-arq/src/main/java/org/apache/jena/riot/system/stream/JenaIOEnvironment.java#L60). Do you want me to make it explicit?

FOAF parse error occurs because without a location mapping, falling back to HTTP doesn't work for FOAF at the moment.
If you change Jena's version to 4.5.0, the error goes away because the mapping is read correctly.

**Comment by afs** [comment]
> a standalone single test case.

There is no location-mapper.ttl configured. Now your saying we have to do that ourselves?

**Comment by namedgraph** [comment]
Not being smart here, just saying that no explicit config was necessary because Jena finds `etc/location-mapping.ttl` by default, and the log shows that. Please see the log.

I can add the config code if you want, but that will not change anything because the problem is not that the mapping cannot be found, but because it cannot be read.

**Comment by namedgraph** [comment]
My question would be, why attempt to read the mapping from any default locations at all? Because it does not seem to have the expected effect.

**Comment by afs** [comment]
"Reader not found:" is an error from jena-core. Not a "can't find" issue. The question is why is that happening?

**Comment by namedgraph** [comment]
At that point `readerFactory .getReader("TURTLE")` is not available:
```
Exception occurred in target VM: Reader not found: TURTLE 
org.apache.jena.shared.NoReaderForLangException: Reader not found: TURTLE
	at org.apache.jena.rdf.model.impl.RDFReaderFImpl.getReader(RDFReaderFImpl.java:60)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:253)
	at org.apache.jena.riot.system.stream.JenaIOEnvironment.createLocationMapper(JenaIOEnvironment.java:185)
	at org.apache.jena.riot.system.stream.JenaIOEnvironment.getLocationMapper(JenaIOEnvironment.java:47)
	at org.apache.jena.riot.system.stream.StreamManager.createStd(StreamManager.java:59)
	at org.apache.jena.riot.system.stream.StreamManager.<clinit>(StreamManager.java:97)
	at org.apache.jena.riot.adapters.AdapterFileManager.makeGlobal(AdapterFileManager.java:154)
	at org.apache.jena.riot.adapters.AdapterFileManager.get(AdapterFileManager.java:114)
	at org.apache.jena.riot.system.IO_JenaReaders.wireIntoJena(IO_JenaReaders.java:37)
	at org.apache.jena.riot.IO_Jena.wireIntoJena(IO_Jena.java:30)
	at org.apache.jena.riot.RIOT.init(RIOT.java:80)
	at org.apache.jena.riot.system.InitRIOT.start(InitRIOT.java:29)
	at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
	at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88)
	at com.atomgraph.spinrdf.model.InfOntModelCommandImplTest.<clinit>(InfOntModelCommandImplTest.java:48)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```
Call stack:
```
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:253)
	at org.apache.jena.riot.system.stream.JenaIOEnvironment.createLocationMapper(JenaIOEnvironment.java:185)
	at org.apache.jena.riot.system.stream.JenaIOEnvironment.getLocationMapper(JenaIOEnvironment.java:47)
	at org.apache.jena.riot.system.stream.StreamManager.createStd(StreamManager.java:59)
	at org.apache.jena.riot.system.stream.StreamManager.<clinit>(StreamManager.java:97)
	at org.apache.jena.riot.adapters.AdapterFileManager.makeGlobal(AdapterFileManager.java:154)
	at org.apache.jena.riot.adapters.AdapterFileManager.get(AdapterFileManager.java:114)
	at org.apache.jena.riot.system.IO_JenaReaders.wireIntoJena(IO_JenaReaders.java:37)
	at org.apache.jena.riot.IO_Jena.wireIntoJena(IO_Jena.java:30)
	at org.apache.jena.riot.RIOT.init(RIOT.java:80)
	at org.apache.jena.riot.system.InitRIOT.start(InitRIOT.java:29)
	at org.apache.jena.base.module.Subsystem.lambda$initialize$2(Subsystem.java:117)
	at org.apache.jena.base.module.Subsystem$$Lambda$27/0x0000000800c20e10.accept
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
	at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
	at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:88)
	at com.atomgraph.spinrdf.model.InfOntModelCommandImplTest.<clinit>(InfOntModelCommandImplTest.java:48)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by afs** [comment]
That what is happening but _why_?

It is because initialization is happening in the wrong order. The global context is allocated in ARQ not RIOT but RIOT is earlier. It is not to do with location mapping per se.

**Comment by namedgraph** [comment]
I understand. That's why I mentioned I have a `JenaSystem.init()` call.

I don't know why but it does not seem to happen with 4.5.0.

**Comment by afs** [comment]
> I don't know why but it does not seem to happen with 4.5.0.

There was an old Turtle parser in jena-core.
https://github.com/apache/jena/issues/1671#issuecomment-1351542816
