### ISSUE TITLE
Make Fuseki compatible with Jakarta

### ISSUE THREAD

**Issue by LuLeRoemer** [apache/jena#1763]
### Version

4.7.0

### Feature

We are trying to use the embedded Fuseki server with Spring Boot version 3.0.1. Unfortunately, we run into a problem where we get a `ClassNotFoundException` exception for `javax.servlet.ServletContext`. I assume this is due to the fact that `jena-fuseki-core` in version 4.7.0 uses `jetty-servlets` in version 10.0.12. From what I understand, the next major version (11) of `jetty-servlets` replaces `javax.*` with the `jakarta.*` API that Spring Boot provides. As described [here](https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0), we cannot mix the two.

### Are you interested in contributing a solution yourself?

No

**Comment by afs** [comment]
The blocker is the WAR file which shares `jena-fuseki-core`.

That locks to specific versions of Apache Tomcat (Tomcat 10 being the first Jakarka based Tomcat).

There are also the Spring Boot 2 users.
Spring Boot 3 was only a few moths ago - Nov 2022 

See preparation work : #1643

**Comment by afs** [comment]
Seeking information: [email to users@ asking about tomcat usage](https://lists.apache.org/thread/go9wxd05zcpj2g4hmnvvb7jvf4p81r6g).

**Comment by rzo1** [comment]
> The migration Jakarta 8 to Jakarta 9 is only renaming. It's not all javax.* but identifying which and running the maven shade plugin should perform this conversion. (There are others tools.)

Maven Shade works just fine. We are using it in several ASF projects (Geronimo, Johnzon, TomEE, ...) to provide Jakarta ready artifacts via Maven classifiers. It has some drawbacks, but it is most likely a quick win rather than dropping javax support completly :-)

**Comment by afs** [comment]
@rzo1,

presumably this works in reverse as well -- convert `jakarta.*` to `javax.*` (providing no new capabilities of the various specs are used).

There is likely to be a long tail on javax.* usage because of SpringBoot2 and general slowness of updating to recent Tomcat releases.

If this "down-shading" works, we can move to `jakarta.*` but still have a way of supporting SpringBoot2 and Tomcat<10.

**Comment by afs** [comment]
We plan to switch to jakarka.* at Jena5 (which wil also require Java17).
Conversion to jakarka.* has been tried - it was pretty uneventful.

**Comment by marlewe** [comment]
Hi,

I'm trying to get the Fuseki 5.3.0 .war file working with the Tomcat 10 or 11 docker container. I'd like to connect Fuseki to Tomcat users. 
I'm getting a `java.lang.NoSuchMethodError` while startup (`Shiro environment initialization failed`). It is caused by omnifaces 3.14.6 which still uses javax instead of jakarta.
Tag 4.4 of omnifaces seems to use jakarta at that specific point: `jakarta.enterprise.inject.spi.BeanManager org.omnifaces.util.Beans.getManager()`

I'm not vary familiar with the java world and i'm aware that this may not be the only snippet with a javax/jakarta problem, but maybe it helps at least a bit.

**Comment by afs** [comment]
Hi @marlewe - Could you provide the stacktrace if there is one?

This might be a Shiro issue: The omnifaces jar comes via `shiro-jakarta-ee` (2.0.2 is the latest) and I've checked the source for that which declares version 3.14.6 (it has updated to 3.14.7 recently) but there is omnifaces v4.x.x series and v5.x coming.

```
[INFO] |  +- org.apache.shiro:shiro-jakarta-ee:jar:jakarta:2.0.2:compile
[INFO] |  |  +- org.omnifaces:omnifaces:jar:3.14.6:compile
[INFO] |  |  \- org.jsoup:jsoup:jar:1.18.1:compile
```

As of Jena 5.3.0, the `jena-fuseki-server` jar is a non-WAR way to run Fuseki and now has the full UI.

**Comment by marlewe** [comment]
Yes, it seems shiro is trying to call that function.
On the long term, i'd like to connect Fuseki to Tomcats SSO possibility, thats why i tried with Tomcat and WAR file.
So since currently there is no WAR-way, I will read about SSO possibilitoes with shiro.

Thanks, @afs 

Log & Stack Trace:
```
27-Feb-2025 10:53:36.597 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/11.0.3
27-Feb-2025 10:53:36.599 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 4 2025 17:40:20 UTC
27-Feb-2025 10:53:36.599 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 11.0.3.0
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            6.8.0-52-generic
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /opt/java/openjdk
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           21.0.6+7-LTS
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Eclipse Adoptium
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
27-Feb-2025 10:53:36.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
27-Feb-2025 10:53:36.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
27-Feb-2025 10:53:36.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
27-Feb-2025 10:53:36.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
27-Feb-2025 10:53:36.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.io.useCanonCaches=false
27-Feb-2025 10:53:36.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --enable-native-access=ALL-UNNAMED
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
27-Feb-2025 10:53:36.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
27-Feb-2025 10:53:36.610 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [2.0.8] using APR version [1.7.2].
27-Feb-2025 10:53:36.613 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 3.0.13 30 Jan 2024]
27-Feb-2025 10:53:36.791 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
27-Feb-2025 10:53:36.801 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [302] milliseconds
27-Feb-2025 10:53:36.822 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
27-Feb-2025 10:53:36.822 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/11.0.3]
27-Feb-2025 10:53:36.838 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/fuseki.war]
27-Feb-2025 10:53:39.453 INFO [main] org.apache.catalina.core.StandardContext.checkUnusualURLPattern Suspicious URL pattern: [/#*] in context [/fuseki], see sections 12.1 and 12.2 of the Servlet specification
27-Feb-2025 10:53:39.499 WARNING [main] org.apache.catalina.startup.ContextConfig.validateSecurityRoles Security role name [tomcat] used in an <auth-constraint> without being defined in a <security-role>
27-Feb-2025 10:53:39.550 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ERROR: EnvironmentLoader.java:155: Shiro environment initialization failed
java.lang.NoSuchMethodError: 'jakarta.enterprise.inject.spi.BeanManager org.omnifaces.util.Beans.getManager()'
     at org.apache.shiro.ee.listeners.IniEnvironment$SecurityManagerFactory.generateCipherKey(IniEnvironment.java:77)
     at org.apache.shiro.mgt.AbstractRememberMeManager.<init>(AbstractRememberMeManager.java:111)
     at org.apache.shiro.web.mgt.CookieRememberMeManager.<init>(CookieRememberMeManager.java:98)
     at org.apache.shiro.web.mgt.DefaultWebSecurityManager.init(DefaultWebSecurityManager.java:108)
     at org.apache.shiro.web.mgt.DefaultWebSecurityManager.<init>(DefaultWebSecurityManager.java:82)
     at org.apache.shiro.ee.listeners.IniEnvironment$SecurityManagerFactory.createDefaultInstance(IniEnvironment.java:73)
     at org.apache.shiro.ini.IniSecurityManagerFactory.createDefaults(IniSecurityManagerFactory.java:174)
     at org.apache.shiro.web.config.WebIniSecurityManagerFactory.createDefaults(WebIniSecurityManagerFactory.java:73)
     at org.apache.shiro.ee.listeners.IniEnvironment$SecurityManagerFactory.createDefaults(IniEnvironment.java:58)
     at org.apache.shiro.ini.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:151)
     at org.apache.shiro.ini.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:120)
     at org.apache.shiro.ini.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:111)
     at org.apache.shiro.ini.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:50)
     at org.apache.shiro.ini.IniFactorySupport.createInstance(IniFactorySupport.java:156)
     at org.apache.shiro.util.AbstractFactory.getInstance(AbstractFactory.java:50)
     at org.apache.shiro.web.env.IniWebEnvironment.createWebSecurityManager(IniWebEnvironment.java:316)
     at org.apache.shiro.web.env.IniWebEnvironment.configure(IniWebEnvironment.java:138)
     at org.apache.shiro.web.env.IniWebEnvironment.init(IniWebEnvironment.java:89)
     at org.apache.shiro.lang.util.LifecycleUtils.init(LifecycleUtils.java:45)
     at org.apache.shiro.lang.util.LifecycleUtils.init(LifecycleUtils.java:40)
     at org.apache.shiro.web.env.EnvironmentLoader.createEnvironment(EnvironmentLoader.java:321)
     at org.apache.shiro.web.env.EnvironmentLoader.initEnvironment(EnvironmentLoader.java:142)
     at org.apache.shiro.ee.listeners.EnvironmentLoaderListener.contextInitialized(EnvironmentLoaderListener.java:84)
     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4019)
     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4444)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:566)
     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:653)
     at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:933)
     at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1875)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
     at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
     at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:735)
     at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:387)
     at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1593)
     at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:267)
     at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:109)
     at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:389)
     at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:336)
     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:743)
     at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
     at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
     at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
     at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
     at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
     at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
     at org.apache.catalina.startup.Catalina.start(Catalina.java:759)
     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
     at java.base/java.lang.reflect.Method.invoke(Method.java:580)
     at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
     at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
27-Feb-2025 10:53:39.679 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
27-Feb-2025 10:53:39.682 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/fuseki] startup failed due to previous errors
27-Feb-2025 10:53:39.693 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/fuseki.war] has finished in [2,854] ms
27-Feb-2025 10:53:39.696 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
27-Feb-2025 10:53:39.706 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [2904] milliseconds
```

**Comment by afs** [comment]
PR #3039 should address the Omnifaces issue.

A development build is available from the [snapshots repository](https://repository.apache.org/content/repositories/snapshots/org/apache/jena/jena-fuseki-war/)

The war file may see limited development. The `fuseki-server.jar` will probably be a better choice for you. Fuseki Modules offer a more flexibility way to add functionality to the core server.

Please reopen this issue if any further problems arise.
