### ISSUE TITLE
RDF-star query builder, triple check throws when subject is Node_Triple

### ISSUE THREAD

**Issue by tkaryadis** [apache/jena#1874]
### Version

4.8.0

### What happened?

I wanted to write this simple RDF-star query using the Jena query builder : 
And because the subject is Triple, it threw exception, probably the triple check function not updated yet for RDF-star.

```sparql
SELECT  ?city
WHERE
  { << <https://squery.org/joy/athens> <https://squery.org/joy/connected> ?city >>
              <https://squery.org/joy/distance>  500}
```

My code :
```java
var athens = ResourceFactory.createResource( "https://squery.org/joy/athens").asNode();
var connected =ResourceFactory.createProperty( "https://squery.org/joy/connected").asNode();
var city_var  = Var.alloc("city").asNode();

Node_Triple node_triple = new Node_Triple(athens,connected,city_var);

var distance = ResourceFactory.createResource(  "https://squery.org/joy/distance").asNode();
var l500 = ResourceFactory.createTypedLiteral( 500).asNode();

 Triple triple = Triple.create(node_triple,distance,l500);

  SelectBuilder s = new SelectBuilder();
        var q=
        s.addVar("?city")        
        .addWhere(triple)
        .build()
        .toString();
    
   System.out.println(q);
```

Exception : 
```java
Exception in thread "main" java.lang.IllegalArgumentException: Subject (<< https://squery.org/joy/athens @https://squery.org/joy/connected ?city >>) must be a URI, blank, variable, or a wildcard. 
Is a prefix missing?  Prefix must be defined before use. 

        at org.apache.jena.arq.querybuilder.handlers.WhereHandler.testTriple(WhereHandler.java:200)
        at org.apache.jena.arq.querybuilder.handlers.WhereHandler.addWhere(WhereHandler.java:212)
        at org.apache.jena.arq.querybuilder.SelectBuilder.addWhere(SelectBuilder.java:307)
        at org.apache.jena.arq.querybuilder.MyMain.main(MyMain.java:44)
```        
I used the source code and i comment the error checking on querybuilder/handlers/wherehandler,
private static void testTriple(TriplePath t)    function and it worked, maybe the wherehanlder is not updated for RDF-star,
and throws exception. After making comment the //throw new IllegalArgumentException(sb.toString());

I got the expected output : 

```sparql
SELECT  ?city
WHERE
  { << <https://squery.org/joy/athens> <https://squery.org/joy/connected> ?city >>
              <https://squery.org/joy/distance>  "500"^^<http://www.w3.org/2001/XMLSchema#int>}
```        

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
It does appear that the query build has not been updated for RDF-star yet.

The validity check need `.isNodeTriple()` added - the question is then whether other places need updating.

Quoted triples can also occur in VALUES clauses and expressions.

**Comment by Claudenw** [comment]
The UpdateBuilder is missing the Node_Triple check.
