### ISSUE TITLE
HttpLib throws NullPointerException if body is null.

### ISSUE THREAD

**Issue by koettert** [apache/jena#1902]
### Version

4.7.0

### What happened?

This bug not only affect 4.7 but also 4.8 and the main branch.
Executing a certain query results in a httpStatusCode in the range of 400 to 499. This results in the call of the [exception()](https://github.com/apache/jena/blob/main/jena-arq/src/main/java/org/apache/jena/http/HttpLib.java#L233) method which expects a response body in [line 241](https://github.com/apache/jena/blob/main/jena-arq/src/main/java/org/apache/jena/http/HttpLib.java#L241). However the body is null which results in the _NullPointerException_ in the attached stacktrace.

### Relevant output and stacktrace

```shell
2023-04-13 16:27:33,289 : ERROR : KNIME-Worker-1-SPARQL Query 3:1 :  : Node : SPARQL Query : 3:1 : Execute failed: ("TripleStoreException"): null
org.knime.semanticweb.utility.TripleStoreException
      at org.knime.semanticweb.utility.SemanticWebUtility.executeQuery(SemanticWebUtility.java:405)
      at org.knime.semanticweb.nodes.query.SPARQLQueryNodeModel.run(SPARQLQueryNodeModel.java:170)
      at org.knime.semanticweb.nodes.query.SPARQLQueryNodeModel.execute(SPARQLQueryNodeModel.java:203)
      at org.knime.core.node.NodeModel.executeModel(NodeModel.java:549)
      at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1267)
      at org.knime.core.node.Node.execute(Node.java:1041)
      at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:595)
      at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:98)
      at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:201)
      at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:117)
      at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:367)
      at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:221)
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
      at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
      at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
      at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
Caused by: java.lang.NullPointerException
      at java.base/java.io.Reader.<init>(Unknown Source)
      at java.base/java.io.InputStreamReader.<init>(Unknown Source)
      at org.apache.jena.atlas.io.IO.asUTF8(IO.java:207)
      at org.apache.jena.atlas.io.IO.readWholeFileAsUTF8(IO.java:456)
      at org.apache.jena.http.HttpLib.exception(HttpLib.java:241)
      at org.apache.jena.http.HttpLib.handleHttpStatusCode(HttpLib.java:173)
      at org.apache.jena.sparql.exec.http.QueryExecHTTP.executeQuery(QueryExecHTTP.java:546)
      at org.apache.jena.sparql.exec.http.QueryExecHTTP.execRowSet(QueryExecHTTP.java:172)
      at org.apache.jena.sparql.exec.http.QueryExecHTTP.select(QueryExecHTTP.java:163)
      at org.apache.jena.sparql.exec.QueryExecutionAdapter.execSelect(QueryExecutionAdapter.java:117)
      at org.knime.semanticweb.utility.SemanticWebUtility.executeQuery(SemanticWebUtility.java:396)
      ... 15 more
```

### Are you interested in making a pull request?

Maybe

**Comment by koettert** [comment]
Thanks @afs for the super quick fix!

**Comment by koettert** [comment]
Any idea when the next bug fix release will be published?

**Comment by afs** [comment]
Jena releases every 3-4 months on a tick. We last released at the beginning of May. I'm hoping/expecting to do a release in July. The project can't promise a specific date because we are volunteers.

You can welcome to test the daily development version - maven repo https://repository.apache.org/content/repositories/snapshots/ version 4.9.0-SNAPSHOT

but note these are not official releases of the Apache Software Foundation.

I'm not completely clear why the body was null. The javadoc suggests a redirection or authentication happened but the stacktrace doesn't go into those details.

**Comment by koettert** [comment]
I perfectly understand that you cannot promise any specific date :-) Looking forward to it.
We are also not clear why the request returns an empty body and still investigate the problem. If we find anything I will report back here.

**Comment by afs** [comment]
Thanks - always good to know what the root cause it.
