### ISSUE TITLE
MurmurHash3 NoSuchMethodError

### ISSUE THREAD

**Issue by larisa1995** [apache/jena#2104]
### Version

apache-jena-4.8.0

### What happened?

Trying my best to run binary RMLStreamer [1] on Windows. Got the following error.

I would be grateful if you could tell me how to fix this. Found a similar issue from 2020 if it helps [2].

[1] https://github.com/RMLio/RMLStreamer
[2] https://issues.apache.org/jira/browse/JENA-1925?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=17144916#comment-17144916

java.lang.NoSuchMethodError: org.apache.commons.codec.digest.MurmurHash3.hash128x64([B)[J
        at org.apache.jena.riot.lang.BlankNodeAllocatorHash.alloc(BlankNodeAllocatorHash.java:138)
        at org.apache.jena.riot.lang.BlankNodeAllocatorHash.create(BlankNodeAllocatorHash.java:111)
        at org.apache.jena.riot.lang.LabelToNode$Alloc.create(LabelToNode.java:187)
        at org.apache.jena.riot.lang.LabelToNode$Alloc.create(LabelToNode.java:178)
        at org.apache.jena.riot.system.MapWithScope.create(MapWithScope.java:86)
        at org.apache.jena.riot.system.FactoryRDFStd.createBlankNode(FactoryRDFStd.java:97)
        at org.apache.jena.riot.system.ParserProfileStd.createBlankNode(ParserProfileStd.java:220)
        at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:495)
        at org.apache.jena.riot.lang.LangTurtleBase.triplesNodeCompound(LangTurtleBase.java:484)
        at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:469)
        at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:419)
        at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:352)
        at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
        at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:314)
        at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:178)
        at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
        at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:79)
        at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:43)
        at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:186)
        at org.apache.jena.riot.RDFParser.read(RDFParser.java:366)
        at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:356)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:306)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:552)
        at org.apache.jena.riot.RDFDataMgr.parseFromInputStream(RDFDataMgr.java:718)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:253)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:235)
        at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
        at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:253)

### Are you interested in making a pull request?

None

**Comment by kinow** [comment]
Hi @larisa1995 

Did you have a look at the replies in the email thread linked in the JIRA issue? 

https://lists.apache.org/thread/jxl4womxl8co1b3nxzytfd9kozd4z14b

In one of them it is mentioned that it could be because of different versions of commons-codec in the Java classpath. Maybe check your dependency tree (`mvn dependency:tree`) to confirm you don't have an older version of commons-codec loaded.

**Comment by larisa1995** [comment]
@kinow thank you for the answer. It would help a lot if you could possibly elaborate a bit on a tree. I'm a kind of newbie here

**Comment by kinow** [comment]
Not a problem, we are/were all newbies :slightly_smiling_face: 

You said you are working on RMLStreamer. I had a look at the GitHub repository, and it looks like a Maven project (because of the `pom.xml`). Normally Maven projects are built with the `mvn` utility, that will read `pom.xml`, and create a dependency tree.

It will read the dependencies of your `pom.xml`, and the dependencies of your dependencies, and so it goes. Until it has a complete dependency tree.

When you run RMLStreamer (via `mvn` or in an IDE) you are *probably* using the dependencies in your classpath that were installed by Maven (this could vary a lot, and there is no easy way to help you there as it depends on how you are running your code, beyond the scope of an issue here in Apache Jena).

The exception that you have is complaining about a method not found.

>java.lang.NoSuchMethodError: org.apache.commons.codec.digest.MurmurHash3.hash128x64([B)[J

This might be because a) Jena 4.8.0 requires [a version of Commons Codec](https://github.com/apache/jena/blob/jena-4.8.0/pom.xml#L102) but your classpath / dependency tree contains a different version of Commons Codec. It looks like RMLStreamer uses the same version, which is strange. But running `mvn dependency:tree` will print the complete list of dependencies, and you can make sure that you do not have anything else loading another version of commons codec (again, it depends how you are building it.

In your issue description you say that you are using Jena 4.8.0. But RMLStreamer development branch has [jena 4.3.1](https://github.com/RMLio/RMLStreamer/blob/development/pom.xml#L42). Start by making sure you have the correct version of Jena, then `mvn dependency:tree` and look at Commons Codec.

Hope that helps.
