### ISSUE TITLE
Apache Jena Fuseki 4.10.0 throw exception when processing SPARQL

### ISSUE THREAD

**Issue by landong1973** [apache/jena#2269]
### Version

4.10.0

### What happened?

load a simple RDF to the Fuseki server into a named graph `<http://foo.net/test>`

```tel
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix ns1: <http://foo.net/> .
<http://foo.com/project/0314228d> a ns1:Project ;
   dcterms:title "JMOF-DSL-PSM-Parquet-Datatypes" .
```

A simple query like following :

```sparql
PREFIX dct: <http://purl.org/dc/terms/>
select distinct *
where{
graph <http://foo.net/test> {
?s dct:title ?o .
}
}
```

returns a 500 error from the server

Changing any part of the title string would get rid the error. I am wondering what's wrong with the title? does it conflict with any hard coded data type?

### Relevant output and stacktrace

<details>
  <summary>Error BlindingTDB :: get1(?o)</summary>

```shell
Error BlindingTDB :: get1(?o)
org.apache.jena.tdb2.TDBException: NodeTableTRDF/Read

        at org.apache.jena.tdb2.store.nodetable.NodeTableTRDF.readNodeFromTable(NodeTableTRDF.java:87) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableNative._retrieveNodeByNodeId(NodeTableNative.java:102) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableNative.getNodeForNodeId(NodeTableNative.java:52) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableCache._retrieveNodeByNodeId(NodeTableCache.java:208) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableCache.getNodeForNodeId(NodeTableCache.java:133) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableWrapper.getNodeForNodeId(NodeTableWrapper.java:52) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableInline.getNodeForNodeId(NodeTableInline.java:65) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.solver.BindingTDB.get1(BindingTDB.java:126) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.binding.BindingBase.get(BindingBase.java:111) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.binding.BindingProjectBase.get1(BindingProjectBase.java:52) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.binding.BindingBase.get(BindingBase.java:111) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.binding.BindingBase.hashCode(BindingBase.java:191) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.binding.BindingBase.hashCode(BindingBase.java:173) [fuseki-server.jar:4.10.0]

        at java.base/java.util.HashMap.hash(HashMap.java:338) [?:?]

        at java.base/java.util.HashMap.put(HashMap.java:610) [?:?]

        at java.base/java.util.HashSet.add(HashSet.java:221) [?:?]

        at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.hasNextBinding(QueryIterDistinct.java:75) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:38) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:116) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.exec.RowSetStream.hasNext(RowSetStream.java:47) [fuseki-server.jar:4.10.0]

        at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:82) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeQuery(SPARQLQueryProcessor.java:380) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:279) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeWithParameter(SPARQLQueryProcessor.java:224) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:209) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.ActionService.executeLifecycle(ActionService.java:58) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execPost(SPARQLQueryProcessor.java:84) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.ActionProcessor.process(ActionProcessor.java:34) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.ActionBase.process(ActionBase.java:54) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.ActionExecLib.execActionSub(ActionExecLib.java:127) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:101) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:231) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.server.Dispatcher.process(Dispatcher.java:221) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.server.Dispatcher.dispatch(Dispatcher.java:148) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.FusekiFilter.doFilter(FusekiFilter.java:49) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370) [fuseki-server.jar:4.10.0]

        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:334) [fuseki-server.jar:4.10.0]

        at org.apache.jena.fuseki.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:288) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.Server.handle(Server.java:563) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [fuseki-server.jar:4.10.0]

        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [fuseki-server.jar:4.10.0]

        at java.base/java.lang.Thread.run(Thread.java:842) [?:?]

Caused by: org.apache.thrift.protocol.TProtocolException: Unrecognized type 0

        at org.apache.thrift.protocol.TProtocolUtil.skip(TProtocolUtil.java:140) ~[fuseki-server.jar:4.10.0]

        at org.apache.thrift.protocol.TProtocolUtil.skip(TProtocolUtil.java:53) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.riot.thrift.wire.RDF_Term.standardSchemeReadValue(RDF_Term.java:432) ~[fuseki-server.jar:4.10.0]

        at org.apache.thrift.TUnion$TUnionStandardScheme.read(TUnion.java:238) ~[fuseki-server.jar:4.10.0]

        at org.apache.thrift.TUnion$TUnionStandardScheme.read(TUnion.java:227) ~[fuseki-server.jar:4.10.0]

        at org.apache.thrift.TUnion.read(TUnion.java:145) ~[fuseki-server.jar:4.10.0]

        at org.apache.jena.tdb2.store.nodetable.NodeTableTRDF.readNodeFromTable(NodeTableTRDF.java:82) ~[fuseki-server.jar:4.10.0]

        ... 95 more

23:58:56 WARN  Fuseki          :: [573] RC = 500 : null
```
</details>

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
I recreated the described problem with a clean version of installation of Fuseki, with afresh TDB2 database, uploaded the data and executed the query, all using the UI.

The query executes properly, no exception.

The error usually occurs with an existing database that has in the past been silently corrupted by two processes accessing it at the same time. There has also been a report that suggests some non-RDF related program accessing the directory area also may cause a problem.

How are you loading the data?
Does any other application have access to the TDB2 database?

**Comment by landong1973** [comment]
Hi Andy , 

Glad to hear back from you.  
You are right, the Fuseki server works fine after a database reset.  I think there was a database corruption for some reason. 

Please close this case now .
Thanks,
Landong

**Comment by landong1973** [comment]
problem was resolved
