### ISSUE TITLE
Tests for TDB2 fail since "GH-2254: Atomic compaction" (at least on my windows machine)

### ISSUE THREAD

**Issue by arne-bdt** [apache/jena#2315]
### Version

5.0.0-SNAPSHOT

### What happened?

maven clean install on jena-tdb2 fails on my windows machine.

The error seems to have been introduced by the merge for "GH-2254: Atomic compaction" on 02.03.2024 at 17:21.
Before that exact commit the buid was successful. (I created a branch to verify)

### Relevant output and stacktrace

```shell
[ERROR] org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_prefixes_3 -- Time elapsed: 0.126 s <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-38\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-38\Data-0002
	at org.apache.jena.atlas.io.IOX.exception(IOX.java:55)
	at org.apache.jena.tdb2.sys.DatabaseOps.moveDirectory(DatabaseOps.java:443)
	at org.apache.jena.tdb2.sys.DatabaseOps.lambda$compact$3(DatabaseOps.java:395)
	at org.apache.jena.dboe.transaction.txn.TransactionalSystemControl.execReadOnlyDatabase(TransactionalSystemControl.java:45)
	at org.apache.jena.tdb2.sys.DatabaseOps.compact(DatabaseOps.java:377)
	at org.apache.jena.tdb2.sys.DatabaseOps.compact(DatabaseOps.java:317)
	at org.apache.jena.tdb2.DatabaseMgr.compact(DatabaseMgr.java:81)
	at org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_prefixes_3_test(TestDatabaseCompact.java:204)
	at org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_prefixes_3(TestDatabaseCompact.java:167)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-38\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-38\Data-0002
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.jena.tdb2.sys.DatabaseOps.moveDirectory(DatabaseOps.java:442)
	... 46 more
[ERROR] org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_dsg_1 -- Time elapsed: 0.123 s <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-39\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-39\Data-0002
	at org.apache.jena.atlas.io.IOX.exception(IOX.java:55)
	at org.apache.jena.tdb2.sys.DatabaseOps.moveDirectory(DatabaseOps.java:443)
	at org.apache.jena.tdb2.sys.DatabaseOps.lambda$compact$3(DatabaseOps.java:395)
	at org.apache.jena.dboe.transaction.txn.TransactionalSystemControl.execReadOnlyDatabase(TransactionalSystemControl.java:45)
	at org.apache.jena.tdb2.sys.DatabaseOps.compact(DatabaseOps.java:377)
	at org.apache.jena.tdb2.sys.DatabaseOps.compact(DatabaseOps.java:317)
	at org.apache.jena.tdb2.DatabaseMgr.compact(DatabaseMgr.java:81)
	at org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_dsg_1(TestDatabaseCompact.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-39\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-39\Data-0002
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.jena.tdb2.sys.DatabaseOps.moveDirectory(DatabaseOps.java:442)
	... 45 more
[ERROR] org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_graph_2 -- Time elapsed: 0.124 s <<< ERROR!
org.apache.jena.atlas.RuntimeIOException: java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-42\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-42\Data-0002
	at org.apache.jena.atlas.io.IOX.exception(IOX.java:55)
	at org.apache.jena.tdb2.sys.DatabaseOps.moveDirectory(DatabaseOps.java:443)
	at org.apache.jena.tdb2.sys.DatabaseOps.lambda$compact$3(DatabaseOps.java:395)
	at org.apache.jena.dboe.transaction.txn.TransactionalSystemControl.execReadOnlyDatabase(TransactionalSystemControl.java:45)
	at org.apache.jena.tdb2.sys.DatabaseOps.compact(DatabaseOps.java:377)
	at org.apache.jena.tdb2.sys.DatabaseOps.compact(DatabaseOps.java:317)
	at org.apache.jena.tdb2.DatabaseMgr.compact(DatabaseMgr.java:81)
	at org.apache.jena.tdb2.sys.TestDatabaseCompact.compact_graph_2(TestDatabaseCompact.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-42\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-42\Data-0002
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.apache.jena.tdb2.sys.DatabaseOps.moveDirectory(DatabaseOps.java:442)
	... 45 more

[ERROR] Errors: 
[ERROR]   TestDatabaseCompact.compact_dsg_1:84 » RuntimeIO java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-39\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-39\Data-0002
[ERROR]   TestDatabaseCompact.compact_graph_2:120 » RuntimeIO java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-42\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-42\Data-0002
[ERROR]   TestDatabaseCompact.compact_prefixes_3:167->compact_prefixes_3_test:204 » RuntimeIO java.nio.file.AccessDeniedException: C:\rd\jena\jena-tdb2\target\tdb-testing\D-38\Data-0002-tmp -> C:\rd\jena\jena-tdb2\target\tdb-testing\D-38\Data-0002
[INFO] 
[ERROR] Tests run: 749, Failures: 0, Errors: 3, Skipped: 7
```

### Are you interested in making a pull request?

No

**Comment by afs** [comment]
@arne-bdt Thanks for the report and thanks for taking the time to pin down the commit.
