### ISSUE TITLE
Intermittent test failure in UI build

### ISSUE THREAD

**Issue by afs** [apache/jena#2331]
### Version

5.0.0 dev

### What happened?

See attached log file for the complete log of this step.

It does not happen all the time. I tried three runs and it happened once.

```
[INFO] [TESTS]   8 passing (28s)
[INFO] [TESTS]   1 failing
[INFO] [TESTS] 
[INFO] [TESTS]   1) datasets
[INFO] [TESTS]        after creating new datasets
[INFO] [TESTS]          Visualizes the dataset information (Info View, tab):
[INFO] [TESTS]      AssertionError: Timed out retrying after 20000ms: Expected to find element: `table#dataset-size-table > tbody > tr > td`, but never found it.
[INFO] [TESTS]       at Context.eval (http://localhost:36851/__cypress/tests?p=tests/e2e/specs/datasets.cy.js:106:60)
[INFO] [TESTS] 
```
This does not fail the build.

### Are you interested in making a pull request?

No

**Comment by afs** [comment]
[ui-test-run.txt](https://github.com/apache/jena/files/14579095/ui-test-run.txt)

**Comment by kinow** [comment]
Text file above is 404 for me.

**Comment by afs** [comment]
<details>
<summary>ui-test-run</summary>

```
[INFO] --- frontend:1.15.0:yarn (yarn run test:e2e) @ jena-fuseki-ui ---
[INFO] Running 'yarn run test:e2e' in /home/afs/ASF/jena-review/jena-fuseki2/jena-fuseki-ui
[INFO] yarn run v1.22.17
[INFO] $ cross-env FUSEKI_PORT="${FUSEKI_PORT:=3030}" PORT="${PORT:=8080}" concurrently --names 'SERVER,CLIENT,TESTS' --prefix-colors 'yellow,blue,green' --success 'first' --kill-others 'yarn run serve:fuseki' 'yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev' 'yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@'
[INFO] [CLIENT] $ /home/afs/ASF/jena-review/jena-fuseki2/jena-fuseki-ui/node_modules/.bin/wait-on 'http://localhost:42053/$/ping'
[INFO] [TESTS] $ /home/afs/ASF/jena-review/jena-fuseki2/jena-fuseki-ui/node_modules/.bin/wait-on http-get://localhost:36851/index.html
[INFO] [SERVER] $ nodemon src/services/mock/json-server.js
[INFO] [SERVER] [nodemon] 3.1.0
[INFO] [SERVER] [nodemon] to restart at any time, enter `rs`
[INFO] [SERVER] [nodemon] watching path(s): *.*
[INFO] [SERVER] [nodemon] watching extensions: js,mjs,cjs,json
[INFO] [SERVER] [nodemon] starting `node src/services/mock/json-server.js`
[INFO] [SERVER] JSON Server is running
[INFO] [SERVER] HEAD /$/ping 200 2.816 ms - 40
[INFO] [CLIENT] $ vite
[INFO] [CLIENT] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
[INFO] [CLIENT] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
[INFO] [CLIENT] Re-optimizing dependencies because lockfile has changed
[INFO] [CLIENT] 
[INFO] [CLIENT]   VITE v5.1.4  ready in 260 ms
[INFO] [CLIENT] 
[INFO] [CLIENT]   ➜  Local:   http://localhost:36851/
[INFO] [CLIENT]   ➜  Network: use --host to expose
[INFO] [SERVER] GET /index.html 200 0.235 ms - 2
[INFO] [TESTS] 
[INFO] [TESTS] DevTools listening on ws://127.0.0.1:40463/devtools/browser/6c89e177-3ea2-4b48-bdb0-4c1645414d4d
[INFO] [TESTS] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
[INFO] [TESTS] Warning: Multiple attempts to register the following task(s):
[INFO] [TESTS] 
[INFO] [TESTS]  - resetCoverage
[INFO] [TESTS]  - combineCoverage
[INFO] [TESTS]  - coverageReport
[INFO] [TESTS] 
[INFO] [TESTS] Only the last attempt will be registered.
[INFO] [TESTS] 
[INFO] [TESTS] ================================================================================
[INFO] [TESTS] 
[INFO] [TESTS]   (Run Starting)
[INFO] [TESTS] 
[INFO] [TESTS]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[INFO] [TESTS]   │ Cypress:        13.6.6                                                                         │
[INFO] [TESTS]   │ Browser:        Electron 118 (headless)                                                        │
[INFO] [TESTS]   │ Node Version:   v20.11.0 (/home/afs/ASF/jena-review/jena-fuseki2/jena-fuseki-ui/node/node)     │
[INFO] [TESTS]   │ Specs:          2 found (datasets.cy.js, query.cy.js)                                          │
[INFO] [TESTS]   │ Searched:       tests/e2e/specs/**/*.cy.{js,jsx,ts,tsx}                                        │
[INFO] [TESTS]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS] ────────────────────────────────────────────────────────────────────────────────────────────────────
[INFO] [TESTS]                                                                                                     
[INFO] [TESTS]   Running:  datasets.cy.js                                                                  (1 of 2)
[INFO] [TESTS] The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
[INFO] [TESTS] Generated an empty chunk: "index".
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   datasets
[INFO] [TESTS]     without any datasets
[INFO] [SERVER] GET /tests/reset 200 0.435 ms - 2
[INFO] [SERVER] GET /$/ping 200 0.186 ms - 40
[INFO] [SERVER] GET /$/server 200 0.161 ms - 104
[INFO] [TESTS]       ✓ Visits datasets page, also the application landing-page (2159ms)
[INFO] [SERVER] GET /$/ping 200 0.239 ms - 40
[INFO] [SERVER] GET /$/server 304 0.189 ms - -
[INFO] [SERVER] GET /$/server 200 0.148 ms - 104
[INFO] [SERVER] GET /tests/reset 200 0.577 ms - 2
[INFO] [TESTS]       ✓ Filters without any data (369ms)
[INFO] [TESTS]     after creating new datasets
[INFO] [SERVER] GET /tests/reset 200 0.168 ms - 2
[INFO] [SERVER] GET /$/ping 200 0.199 ms - 40
[INFO] [SERVER] POST /$/datasets 200 29.219 ms - 2
[INFO] [SERVER] GET /$/server 200 0.177 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.378 ms - 2
[INFO] [SERVER] GET /$/server 200 0.165 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.626 ms - 2
[INFO] [SERVER] GET /$/server 200 0.169 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.727 ms - 2
[INFO] [SERVER] GET /$/server 200 0.382 ms - -
[INFO] [SERVER] POST /$/datasets 200 1.216 ms - 2
[INFO] [SERVER] GET /$/server 200 0.594 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.781 ms - 2
[INFO] [SERVER] GET /$/server 200 0.484 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.840 ms - 2
[INFO] [SERVER] GET /$/server 200 0.276 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.456 ms - 2
[INFO] [SERVER] GET /$/server 200 0.428 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.399 ms - 2
[INFO] [SERVER] GET /$/server 200 0.210 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.397 ms - 2
[INFO] [SERVER] GET /$/server 200 0.369 ms - -
[INFO] [SERVER] POST /$/datasets 200 0.343 ms - 2
[INFO] [SERVER] GET /$/server 200 0.283 ms - -
[INFO] [SERVER] GET /$/server 200 0.204 ms - -
[INFO] [SERVER] GET /$/stats/a 200 0.463 ms - -
[INFO] [SERVER] GET /a/sparql?query=select+(count(*)+as+%3Fcount)+%7B%3Fs+%3Fp+%3Fo%7D 200 0.274 ms - 259
[INFO] [SERVER] GET /a/sparql?query=select+%3Fg+(count(*)+as+%3Fcount)+%7Bgraph+%3Fg+%7B%3Fs+%3Fp+%3Fo%7D%7D+group+by+%3Fg 200 0.201 ms - 103
[INFO] [SERVER] GET /a/data?graph=default 200 0.171 ms - 257
[INFO] [TESTS]       ✓ Edits the graph (3944ms)
[INFO] [SERVER] GET /$/ping 200 0.183 ms - 40
[INFO] [SERVER] GET /$/server 304 0.243 ms - -
[INFO] [TESTS]       ✓ Visits datasets page (151ms)
[INFO] [SERVER] GET /$/ping 200 0.146 ms - 40
[INFO] [SERVER] GET /$/server 304 0.147 ms - -
[INFO] [SERVER] GET /$/server 304 0.201 ms - -
[INFO] [TESTS]       ✓ Uses the table pagination (187ms)
[INFO] [SERVER] GET /$/ping 200 0.196 ms - 40
[INFO] [SERVER] GET /$/server 304 0.162 ms - -
[INFO] [TESTS]       ✓ Sorts the table (343ms)
[INFO] [SERVER] GET /$/ping 200 0.146 ms - 40
[INFO] [SERVER] GET /$/server 200 0.194 ms - -
[INFO] [TESTS]       ✓ Filters the table (384ms)
[INFO] [SERVER] GET /$/ping 200 0.132 ms - 40
[INFO] [SERVER] GET /$/server 304 0.216 ms - -
[INFO] [SERVER] GET /$/server 304 0.203 ms - -
[INFO] [SERVER] POST /$/datasets 409 0.346 ms - 37
[INFO] [TESTS]       ✓ Cannot add two datasets with the same name (473ms)
[INFO] [SERVER] GET /$/ping 200 0.144 ms - 40
[INFO] [SERVER] GET /$/server 200 0.170 ms - -
[INFO] [SERVER] GET /$/stats/a 304 0.159 ms - -
[INFO] [SERVER] GET /$/ping 200 0.171 ms - 40
[INFO] [SERVER] GET /$/ping 200 0.483 ms - 40
[INFO] [SERVER] GET /$/ping 200 0.492 ms - 40
[INFO] [SERVER] GET /$/ping 200 0.377 ms - 40
[INFO] [TESTS]       1) Visualizes the dataset information (Info View, tab)
[INFO] [SERVER] GET /tests/reset 200 0.141 ms - 2
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   8 passing (28s)
[INFO] [TESTS]   1 failing
[INFO] [TESTS] 
[INFO] [TESTS]   1) datasets
[INFO] [TESTS]        after creating new datasets
[INFO] [TESTS]          Visualizes the dataset information (Info View, tab):
[INFO] [TESTS]      AssertionError: Timed out retrying after 20000ms: Expected to find element: `table#dataset-size-table > tbody > tr > td`, but never found it.
[INFO] [TESTS]       at Context.eval (http://localhost:36851/__cypress/tests?p=tests/e2e/specs/datasets.cy.js:106:60)
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   (Results)
[INFO] [TESTS] 
[INFO] [TESTS]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[INFO] [TESTS]   │ Tests:        9                                                                                │
[INFO] [TESTS]   │ Passing:      8                                                                                │
[INFO] [TESTS]   │ Failing:      1                                                                                │
[INFO] [TESTS]   │ Pending:      0                                                                                │
[INFO] [TESTS]   │ Skipped:      0                                                                                │
[INFO] [TESTS]   │ Screenshots:  1                                                                                │
[INFO] [TESTS]   │ Video:        false                                                                            │
[INFO] [TESTS]   │ Duration:     28 seconds                                                                       │
[INFO] [TESTS]   │ Spec Ran:     datasets.cy.js                                                                   │
[INFO] [TESTS]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   (Screenshots)
[INFO] [TESTS] 
[INFO] [TESTS]   -  /home/afs/ASF/jena-review/jena-fuseki2/jena-fuseki-ui/tests/e2e/screenshots/data     (1280x720)
[INFO] [TESTS]      sets.cy.js/datasets -- after creating new datasets -- Visualizes the dataset inf               
[INFO] [TESTS]      ormation (Info View, tab) (failed).png                                                         
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS] ────────────────────────────────────────────────────────────────────────────────────────────────────
[INFO] [TESTS]                                                                                                     
[INFO] [TESTS]   Running:  query.cy.js                                                                     (2 of 2)
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   Query
[INFO] [SERVER] GET /tests/reset 200 0.121 ms - 2
[INFO] [SERVER] GET /$/ping 200 0.135 ms - 40
[INFO] [SERVER] POST /$/datasets 200 0.634 ms - 2
[INFO] [SERVER] GET /$/server 200 0.187 ms - -
[INFO] [SERVER] GET /$/server 304 0.181 ms - -
[INFO] [SERVER] GET /$/stats/skosmos 200 0.146 ms - -
[INFO] [SERVER] GET /tests/reset 200 0.141 ms - 2
[INFO] [TESTS]     ✓ Uses the correct SPARQL Endpoint (1437ms)
[INFO] [SERVER] GET /tests/reset 200 0.193 ms - 2
[INFO] [SERVER] GET /$/ping 200 0.139 ms - 40
[INFO] [SERVER] POST /$/datasets 200 0.575 ms - 2
[INFO] [SERVER] GET /$/server 200 0.149 ms - -
[INFO] [SERVER] GET /$/server 304 0.150 ms - -
[INFO] [SERVER] GET /$/stats/skosmos 304 0.158 ms - -
[INFO] [SERVER] GET /tests/reset 200 0.157 ms - 2
[INFO] [TESTS]     ✓ Can resize the query editor (906ms)
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   2 passing (2s)
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]   (Results)
[INFO] [TESTS] 
[INFO] [TESTS]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[INFO] [TESTS]   │ Tests:        2                                                                                │
[INFO] [TESTS]   │ Passing:      2                                                                                │
[INFO] [TESTS]   │ Failing:      0                                                                                │
[INFO] [TESTS]   │ Pending:      0                                                                                │
[INFO] [TESTS]   │ Skipped:      0                                                                                │
[INFO] [TESTS]   │ Screenshots:  0                                                                                │
[INFO] [TESTS]   │ Video:        false                                                                            │
[INFO] [TESTS]   │ Duration:     2 seconds                                                                        │
[INFO] [TESTS]   │ Spec Ran:     query.cy.js                                                                      │
[INFO] [TESTS]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS] ================================================================================
[INFO] [TESTS] 
[INFO] [TESTS]   (Run Finished)
[INFO] [TESTS] 
[INFO] [TESTS] 
[INFO] [TESTS]        Spec                                              Tests  Passing  Failing  Pending  Skipped  
[INFO] [TESTS]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[INFO] [TESTS]   │ ✖  datasets.cy.js                           00:28        9        8        1        -        - │
[INFO] [TESTS]   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
[INFO] [TESTS]   │ ✔  query.cy.js                              00:02        2        2        -        -        - │
[INFO] [TESTS]   └────────────────────────────────────────────────────────────────────────────────────────────────┘
[INFO] [TESTS]     ✖  1 of 2 failed (50%)                      00:30       11       10        1        -        -  
[INFO] [TESTS] 
[INFO] [TESTS] yarn wait-on http-get://localhost:${PORT}/index.html && cypress run $@ exited with code 1
[INFO] --> Sending SIGTERM to other processes..
[INFO] [SERVER] yarn run serve:fuseki exited with code SIGTERM
[INFO] --> Sending SIGTERM to other processes..
[INFO] [CLIENT] yarn wait-on http://localhost:${FUSEKI_PORT}/$/ping && yarn run dev exited with code SIGTERM
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.error Command failed with exit code 1.
[ERROR] There are test failures.
Failed to run task: 'yarn run test:e2e' failed.
com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'yarn run test:e2e' failed.
    at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute (YarnTaskExecutor.java:64)
    at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute (YarnMojo.java:65)
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutionException: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute (ProcessExecutor.java:82)
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput (ProcessExecutor.java:64)
    at com.github.eirslett.maven.plugins.frontend.lib.YarnExecutor.executeAndRedirectOutput (YarnExecutor.java:28)
    at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute (YarnTaskExecutor.java:58)
    at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute (YarnMojo.java:65)
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.execute (ProcessExecutor.java:74)
    at com.github.eirslett.maven.plugins.frontend.lib.ProcessExecutor.executeAndRedirectOutput (ProcessExecutor.java:64)
    at com.github.eirslett.maven.plugins.frontend.lib.YarnExecutor.executeAndRedirectOutput (YarnExecutor.java:28)
    at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute (YarnTaskExecutor.java:58)
    at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute (YarnMojo.java:65)
    at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute (AbstractFrontendMojo.java:94)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[INFO] 
```

</details>

**Comment by afs** [comment]
<details><summary>screenshot</summary>

![datasets -- after creating new datasets -- Visualizes the dataset information (Info View, tab) (failed)](https://github.com/apache/jena/assets/101362/69f77b65-c452-4a75-bb6f-a540d0891c92)

</details>

**Comment by afs** [comment]
The question is whether to wait a bit for 5.0.0. 
(I can't do the release for a few days anyway.)

**Comment by kinow** [comment]
There are some tests that fail because a) size of viewport, or b) they were working by chance and in some environment things need to be synchronized/locked so that a certain action takes action before another one in the UI.

Normally these are easy to fix, unless it's a real bug (but with the recent changes, I am leaning more on the side of having to update just the test). I'm planning to keep working on Jena a few more days (until this weekend, or the next one), before I have to switch to some Apache Commons work again, so this should be fixed by this weekend or next weekend, hopefully.

Thanks Andy!

**Comment by kinow** [comment]
Reproduced locally! Will troubleshoot it another day :+1:

**Comment by afs** [comment]
Sounds reasonable.  The UI works so no reason to hold-up a release IMO otherwise we get into a state of never being about to release.
