### ISSUE TITLE
org.apache.jena.shared.PrefixMapping$IllegalPrefixException: 😀

### ISSUE THREAD

**Issue by agustaf9** [apache/jena#2383]
### Version

4.9.0

### What happened?

Query fails after uploading file with prefix 😀

`DESCRIBE <https://mydomain.com/myResource> FROM <urn:x-arq:DefaultGraph>`

Fuseki only seems to have an issue when doing `DESCRIBE FROM` and `SELECT FROM`,  `DESCRIBE` and `SELECT` both work fine.

If I understand the trig standard should be a valid prefix.

https://www.w3.org/TR/trig/#grammar-production-PN_CHARS_BASE

### Relevant output and stacktrace

```shell
at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) [fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [fuseki-server.jar:4.9.0]
	at java.lang.Thread.run(Unknown Source) [?:?]
00:17:51 INFO  Fuseki          :: [19130] 500 Server Error (0 ms)
00:17:51 INFO  Fuseki          :: [19129] 500 Server Error (0 ms)
00:21:30 INFO  Fuseki          :: [19131] POST http://fuseki.mydomain.com/ds/sparql
00:21:30 INFO  Fuseki          :: [19131] Query = DESCRIBE <https://mydomain.com/myResource> FROM <urn:x-arq:DefaultGraph>
00:21:30 WARN  Fuseki          :: [19131] RC = 500 : 😀
org.apache.jena.shared.PrefixMapping$IllegalPrefixException: 😀
	at org.apache.jena.shared.impl.PrefixMappingImpl.checkLegal(PrefixMappingImpl.java:181) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.shared.impl.PrefixMappingImpl.setNsPrefix(PrefixMappingImpl.java:80) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.shared.impl.PrefixMappingImpl.setNsPrefixes(PrefixMappingImpl.java:171) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.shared.impl.PrefixMappingImpl.setNsPrefixes(PrefixMappingImpl.java:138) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.graph.GraphUnionRead.lambda$createPrefixMapping$0(GraphUnionRead.java:85) ~[fuseki-server.jar:4.9.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at org.apache.jena.sparql.graph.GraphUnionRead.forEachGraph(GraphUnionRead.java:131) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.graph.GraphUnionRead.createPrefixMapping(GraphUnionRead.java:83) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.graph.impl.GraphBase.getPrefixMapping(GraphBase.java:154) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.core.DatasetGraphMapLink.setDefaultGraph(DatasetGraphMapLink.java:183) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.core.DatasetGraphMapLink.<init>(DatasetGraphMapLink.java:97) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.core.DatasetGraphMapLink.<init>(DatasetGraphMapLink.java:91) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.core.DynamicDatasets.dynamicDataset(DynamicDatasets.java:83) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.sparql.core.DynamicDatasets.dynamicDataset(DynamicDatasets.java:65) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.SPARQL_QueryDataset.decideDatasetDynamic(SPARQL_QueryDataset.java:56) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.SPARQL_QueryDataset.decideDataset(SPARQL_QueryDataset.java:39) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:272) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeWithParameter(SPARQLQueryProcessor.java:224) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:209) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.ActionService.executeLifecycle(ActionService.java:58) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execPost(SPARQLQueryProcessor.java:84) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.ActionProcessor.process(ActionProcessor.java:34) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.ActionBase.process(ActionBase.java:54) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execActionSub(ActionExecLib.java:127) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:101) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:231) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.server.Dispatcher.process(Dispatcher.java:221) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.server.Dispatcher.dispatch(Dispatcher.java:148) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.FusekiFilter.doFilter(FusekiFilter.java:49) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370) ~[fuseki-server.jar:4.9.0]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:334) ~[fuseki-server.jar:4.9.0]
	at org.apache.jena.fuseki.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:288) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) [fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [fuseki-server.jar:4.9.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [fuseki-server.jar:4.9.0]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Are you interested in making a pull request?

None

**Comment by agustaf9** [comment]
I just tried it on 5.0.0 and I get a similar error

**Comment by rvesse** [comment]
This bug report is incomplete. As you note it appears to be triggered by your data but you have failed to provide that data

I would also suggest experimenting with sending different `Accept` headers as it's possible your data has a prefix declaration that is legal for some RDF syntaxes but not others

**Comment by agustaf9** [comment]
Steps to reproduce in a new fuseki dataset:
1. Save data below into a trig file
2. Upload to fuseki using "Add Data" tab in web interface
3. Query `DESCRIBE<https://ex.com/Test1>`  **Returns Result**
4. Query `DESCRIBE<https://ex.com/Test1> FROM <urn:x-arq:DefaultGraph>` **Error 502**

```
@prefix test: <https://ex.com/ontologies/> .
@prefix  😀: <https://ex.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

 😀:Test1 a test:Test ;
    test:title "Test"^^xsd:string ;
.
```

**Comment by afs** [comment]
Fuseki is behind a proxy?

> `org.apache.jena.shared.PrefixMapping$IllegalPrefixException: 😀`

`FROM` triggers `DynamicDatasets.dynamicDataset` which sets up prefixes as it is created at the start of the request, and does not wait until prefixes are used (which would only delay problems to later in the request execution).

While 😀 is a legal prefix name in Turtle family languages, it is not a legal prefix for RDF/XML. That must be a XML NCName to be used in the predicate position. In RDF/XML properties are qnames. 

Jena `PrefixMapping` add restrictions to ensure that, when used to write RDF/XML data, the writing process won't fail because of prefix names. `PrefixMapping` is quite old code and we don't want to change the contract. 

For most processing there is an internal abstraction that supports TriG.

The code in `GraphUnionRead` should skip such prefixes.

**Comment by agustaf9** [comment]
> Fuseki is behind a proxy?
It is running in a container on kubernetes behind a Traefik ingress

**Comment by afs** [comment]
PR #2386 includes allowing "😀" in graph prefix mappings. It turns out that Jena's RDF/XML writing was already quite defensive and converted illegal prefixes (illegal to RDF/XML writing in XML 1.0) to give them a generated legal name. Combine that with ensuring writing RDF/XML follows the more restrictive XML 1.0 with limitation to java char size, then prefixes generally compatible across Turtle TriG etc.
