### ISSUE TITLE
ResultSetException: Datatype is rdf:langString but no language given

### ISSUE THREAD

**Issue by averza** [apache/jena#2555]
### Version

5.0.0

### What happened?

I am running a query on the dbpedia.org SPARQL endpoint. It fails while iterating the result set. Works fine in Jena 4.1.0. Perhaps the data is invalid on dbpedia.org, please investigate.

http://dbpedia.org/sparql
`SELECT DISTINCT * WHERE { <http://dbpedia.org/resource/OpenLink_Software> ?p ?o } LIMIT 100`

### Relevant output and stacktrace

```shell
Exception
=========
org.apache.jena.sparql.resultset.ResultSetException: Datatype is rdf:langString but no language given
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming.moveToNext(RowSetJSONStreaming.java:214)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming.moveToNext(RowSetJSONStreaming.java:66)
	at org.apache.jena.atlas.iterator.IteratorSlotted.hasNext(IteratorSlotted.java:63)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetBuffered.nextFromDelegate(RowSetBuffered.java:165)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetBuffered.moveToNext(RowSetBuffered.java:152)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetBuffered.moveToNext(RowSetBuffered.java:43)
	at org.apache.jena.atlas.iterator.IteratorSlotted.hasNext(IteratorSlotted.java:63)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:75)
	at MyTestProgram
Caused by: org.apache.jena.sparql.resultset.ResultSetException: Datatype is rdf:langString but no language given
	at org.apache.jena.riot.rowset.rw.rs_json.IteratorRsJSON.moveToNext(IteratorRsJSON.java:75)
	at org.apache.jena.atlas.iterator.IteratorSlotted.hasNext(IteratorSlotted.java:63)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming.computeNextActual(RowSetJSONStreaming.java:225)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming.moveToNext(RowSetJSONStreaming.java:210)
	... 19 more
Caused by: org.apache.jena.shared.JenaException: Datatype is rdf:langString but no language given
	at org.apache.jena.graph.NodeFactory.createLiteral(NodeFactory.java:240)
	at org.apache.jena.graph.NodeFactory.createLiteral(NodeFactory.java:177)
	at org.apache.jena.sparql.util.NodeFactoryExtra.createLiteralNode(NodeFactoryExtra.java:100)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming.parseOneTerm(RowSetJSONStreaming.java:404)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming.parseBinding(RowSetJSONStreaming.java:358)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming$RsJsonEltEncoderDft.newBindingElt(RowSetJSONStreaming.java:571)
	at org.apache.jena.riot.rowset.rw.rs_json.RowSetJSONStreaming$RsJsonEltEncoderDft.newBindingElt(RowSetJSONStreaming.java:541)
	at org.apache.jena.riot.rowset.rw.rs_json.IteratorRsJSON.computeNextActual(IteratorRsJSON.java:136)
	at org.apache.jena.riot.rowset.rw.rs_json.IteratorRsJSON.moveToNext(IteratorRsJSON.java:72)
	... 22 more
```

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
> Perhaps the data is invalid on dbpedia.org, please investigate.

Hi @averza -- could you report this issue to OpenLink please?

Even if the data is wrong, the server should not be sending results that do not conform to the results format schema. (The `sparql-results+json` is also wrong).

Putting in a lang tag would be altering the data in a way the application can not detect so this is not a Jena issue.

**Comment by afs** [comment]
The Jena4->Jena5 change is `NodeFactory.createLiteral(NodeFactory.java:240)` and so affects all formats.
