### ISSUE TITLE
RDFXML: can't parse rdf:XMLLiteral when round-trip

### ISSUE THREAD

**Issue by sszuev** [apache/jena#2619]
### Version

5.1.0

### What happened?

Probably this is duplicate of #2473 
Jena produces RDF/XML, which Jena cannot read itself.

```java
String literal =
        "<ncicp:ComplexDefinition>" +
        "<ncicp:def-definition>XXX" +
        "</ncicp:def-definition>" +
        "<ncicp:def-source>NCI-GLOSS</ncicp:def-source></ncicp:ComplexDefinition>";
var m = ModelFactory.createOntologyModel();
m.createResource().addProperty(RDFS.comment, m.createTypedLiteral(literal, RDF.dtXMLLiteral));
StringWriter sw = new StringWriter();
m.write(sw, "rdf/xml");
System.out.println(sw);
StringReader sr = new StringReader(sw.toString());
ModelFactory.createDefaultModel().read(sr, null, "rdf/xml").write(System.out, "ttl");
```

### Relevant output and stacktrace

```shell
Exception in thread "main" org.apache.jena.riot.RiotException: [line: 7, col: 68] The prefix "ncicp" for element "ncicp:ComplexDefinition" is not bound.
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:155)
	at org.apache.jena.riot.lang.rdfxml.rrx.ParserRDFXML_SAX.fatalError(ParserRDFXML_SAX.java:1727)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.apache.jena.riot.lang.rdfxml.rrx.ReaderRDFXML_SAX.parse(ReaderRDFXML_SAX.java:83)
	at org.apache.jena.riot.lang.rdfxml.rrx.ReaderRDFXML_SAX.read(ReaderRDFXML_SAX.java:65)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:456)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:442)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:379)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:547)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:72)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:205)
```

### Are you interested in making a pull request?

None

**Comment by namedgraph** [comment]
Where's the `rdf:RDF` root element? It should contain the the namespace declarations.

**Comment by sszuev** [comment]
This is a part of negative test which worked fine on Jena 4.x.
I guess the question "should round-trip work" is reasonable.

**Comment by afs** [comment]
jena4 doesn't seem to write it as an RDF XMLLiteral - it's using `rdf:datatype` not `rdf:parseType="Literal"`

I suspect it is because the implementation of the datatype has changed. It's an illegal RDF XMLLIteral in RDF 1.0

If namespaces are set it work as a `rdf:parseType="Literal"` in jena5

I suspect it is because Jena 5.1.0 has the RDF 1.1 definition of RDF XML Literal.

Jena 4.10 had the RDF 1.0 definition.

Try this, then change the literal to "<ns:text>ABC" -  not handling an illegal rdf:XMLliteral properly.

```java
    public static void main(String... args) {
        String literal = "<ns:text>ABC</ns:text>";
        var m = ModelFactory.createDefaultModel();//createOntologyModel();
        m.createResource().addProperty(RDFS.comment, m.createTypedLiteral(literal, RDF.dtXMLLiteral));
        m.setNsPrefix("ns",  "http://example/");

        System.out.println("---- Lang.TTL");
        RDFWriter.source(m).lang(Lang.TTL).output(System.out);
        System.out.println("---- model - rdf/xml");
        m.write(System.out, "rdf/xml");
        System.out.println("---- RDFFormat.RDFXML_ABBREV");
        RDFWriter.source(m).format(RDFFormat.RDFXML_ABBREV).output(System.out);
        System.out.println("---- RDFFormat.RDFXML_PLAIN");
        RDFWriter.source(m).format(RDFFormat.RDFXML_PLAIN).output(System.out);
        System.out.println("----");

        StringWriter sw = new StringWriter();
        m.write(sw, "rdf/xml");
        System.out.println(sw);
        StringReader sr = new StringReader(sw.toString());
        ModelFactory.createDefaultModel().read(sr, null, "rdf/xml");
        System.out.println("---- done");
    }
```

**Comment by afs** [comment]
> Where's the `rdf:RDF` root element? It should contain the the namespace declarations.

RDF/XML documents of a single element don't need to have `rdf:RDF`. See #2620.

**Comment by afs** [comment]
Changes at Jena5 affected the RDF/XML writer. It does not properly test for a legal `rdf:XMLLiteral`. 

The lexical space of a xml literal must be a self contained XML document fragment - it must include it's namepsaces.
https://www.w3.org/TR/rdf11-concepts/#section-XMLLiteral

The example above is not a valid literal.

It therefore should be written with `rdf:datatype`.
